"""Generate Sapphire-aligned Pine v5 indicators / strategies on demand.

The generated scripts emit JSON alert payloads matching the Sapphire webhook
contract (`services/webhook/`), so a Pine alert that fires routes straight into
the signal pipeline. All output goes to `pine/generated/` so it stays out of
hand-authored sources under `pine/standalone/`.
"""

from __future__ import annotations

import json
import re
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

DEFAULT_GENERATED_ROOT = Path.home() / "Code" / "Sapphire" / "pine" / "generated"
SCHEMA_VERSION = "sapphire.pine_template.v1"

_SAFE_NAME_RE = re.compile(r"[^A-Za-z0-9]+")


def _slug(symbol: str) -> str:
    return _SAFE_NAME_RE.sub("_", symbol).strip("_") or "Symbol"


def render_sapphire_watch_indicator(
    symbol: str,
    *,
    fast_len: int = 12,
    slow_len: int = 26,
    rsi_len: int = 14,
    rsi_ob: int = 70,
    rsi_os: int = 30,
    webhook_payload_extra: dict[str, Any] | None = None,
) -> str:
    """Pine v5 indicator that emits Sapphire-format webhook alerts.

    The payload schema matches what `services/webhook/` expects: symbol,
    action ('long'|'short'|'exit_long'|'exit_short'), price, strategy, ts.
    """
    extra = webhook_payload_extra or {}
    extra_pairs = ", ".join(
        f'\\"{k}\\": \\"{v}\\"' if isinstance(v, str) else f'\\"{k}\\": {v}'
        for k, v in extra.items()
    )
    extra_fragment = f", {extra_pairs}" if extra_pairs else ""
    title = f"Sapphire Watch - {symbol}"
    # Pine's multi-line continuation rules are strict — keep each alert string
    # construction on a single line, matching the production Sapphire_Strategy_Mac.pine.
    payload_prefix = (
        '\'{"symbol": "\' + syminfo.ticker + \'", "action": "'
    )
    # Field name `time` matches the receiver contract in
    # services/webhook/src/receiver.py::TradingViewAlert.from_webhook.
    payload_mid = (
        '", "price": \' + str.tostring(close) + \', '
        '"strategy": "sapphire_watch_indicator", '
        '"source": "tradingview_pine", '
        '"interval": "\' + timeframe.period + \'", '
        '"exchange": "\' + syminfo.prefix + \'", '
        '"time": \' + str.tostring(time) + \''
    )
    payload_suffix = f'{extra_fragment}}}\''
    return f"""// Auto-generated by Sapphire (lib.trading.pine_templates).
// Source-of-truth: regenerate; do not hand-edit.
// Symbol target: {symbol}
//
//@version=5
indicator("{title}", overlay=true)

// Inputs ----------------------------------------------------------------------
fast_len = input.int({fast_len}, "Fast EMA")
slow_len = input.int({slow_len}, "Slow EMA")
rsi_len  = input.int({rsi_len}, "RSI Length")
rsi_ob   = input.int({rsi_ob}, "RSI Overbought")
rsi_os   = input.int({rsi_os}, "RSI Oversold")

// Indicators ------------------------------------------------------------------
fast_ema = ta.ema(close, fast_len)
slow_ema = ta.ema(close, slow_len)
rsi_v    = ta.rsi(close, rsi_len)
[macd_line, signal_line, _] = ta.macd(close, 12, 26, 9)

plot(fast_ema, "Fast EMA", color.new(color.blue, 0), 2)
plot(slow_ema, "Slow EMA", color.new(color.orange, 0), 2)

// Signal logic ----------------------------------------------------------------
long_cond  = ta.crossover(fast_ema, slow_ema) and macd_line > signal_line and rsi_v < rsi_ob
short_cond = ta.crossunder(fast_ema, slow_ema) and macd_line < signal_line and rsi_v > rsi_os
exit_long  = ta.crossunder(fast_ema, slow_ema) or rsi_v > 80
exit_short = ta.crossover(fast_ema, slow_ema)  or rsi_v < 20

plotshape(long_cond,  "LONG",  shape.triangleup,   location.belowbar, color.new(color.green, 0), size=size.small)
plotshape(short_cond, "SHORT", shape.triangledown, location.abovebar, color.new(color.red, 0),   size=size.small)

// Webhook alert payloads (JSON schema matches services/webhook/ contract) ------
if long_cond
    alert({payload_prefix}long{payload_mid}{payload_suffix}, alert.freq_once_per_bar_close)
if short_cond
    alert({payload_prefix}short{payload_mid}{payload_suffix}, alert.freq_once_per_bar_close)
if exit_long
    alert({payload_prefix}exit_long{payload_mid}{payload_suffix}, alert.freq_once_per_bar_close)
if exit_short
    alert({payload_prefix}exit_short{payload_mid}{payload_suffix}, alert.freq_once_per_bar_close)
"""


def write_template(
    name: str,
    pine_source: str,
    *,
    root: Path | str = DEFAULT_GENERATED_ROOT,
    metadata: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Write a Pine source + sidecar metadata into `pine/generated/`.

    Returns a dict with the file paths and metadata for downstream wiring.
    """
    out_root = Path(root)
    out_root.mkdir(parents=True, exist_ok=True)
    safe = _slug(name)
    pine_path = out_root / f"{safe}.pine"
    meta_path = out_root / f"{safe}.json"
    pine_path.write_text(pine_source, encoding="utf-8")
    meta = {
        "schema_version": SCHEMA_VERSION,
        "name": name,
        "slug": safe,
        "generated_at": datetime.now(UTC).replace(microsecond=0).isoformat(),
        "pine_path": str(pine_path),
        "byte_size": len(pine_source.encode("utf-8")),
        **(metadata or {}),
    }
    meta_path.write_text(json.dumps(meta, indent=2, sort_keys=True), encoding="utf-8")
    return {
        "name": name,
        "slug": safe,
        "pine_path": str(pine_path),
        "metadata_path": str(meta_path),
        "metadata": meta,
    }


def list_generated(root: Path | str | None = None) -> list[dict[str, Any]]:
    out_root = Path(root if root is not None else DEFAULT_GENERATED_ROOT)
    if not out_root.exists():
        return []
    rows: list[dict[str, Any]] = []
    for meta_path in sorted(out_root.glob("*.json")):
        try:
            data = json.loads(meta_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if data.get("schema_version") != SCHEMA_VERSION:
            continue
        rows.append(data)
    rows.sort(key=lambda r: r.get("generated_at", ""), reverse=True)
    return rows
