steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/test-app:latest', '-f', 'Dockerfile.test', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/test-app:latest']

options:
  machineType: E2_HIGHCPU_32
  diskSizeGb: 200
