steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_IMAGE}'
      - '-f'
      - 'services/api-gateway/Dockerfile'
      - '.'
    id: 'build-gateway'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']
    id: 'push-gateway'
    waitFor: ['build-gateway']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sapphire-gateway'
      - '--image'
      - '${_IMAGE}'
      - '--region'
      - 'us-central1'
      - '--project'
      - 'sapphire-479610'
      - '--update-secrets'
      - 'SAPPHIRE_CONTROL_API_TOKEN=SAPPHIRE_CONTROL_API_TOKEN:latest'
    id: 'deploy-gateway'
    waitFor: ['push-gateway']

images:
  - '${_IMAGE}'

substitutions:
  _IMAGE: 'gcr.io/sapphire-479610/sapphire-gateway:${SHORT_SHA}'

timeout: 1200s
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
