steps:
  # Build optimized multi-stage container image for cloud-trader (no cache to ensure latest code)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'CACHE_BUST=${BUILD_ID}'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/cloud-trader:${BUILD_ID}'
      - '-t'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/cloud-trader:latest'
      - '--progress=plain'
      - '--target=runtime'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'
      - 'BUILDKIT_PROGRESS=plain'

  # Push cloud-trader container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/cloud-trader:latest'

  # Deploy to GKE cluster
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - -c
      - |
        echo "🔐 Getting GKE credentials..."
        gcloud container clusters get-credentials hft-trading-cluster --zone=us-central1-a --project=${PROJECT_ID}

        echo "🚀 Starting GKE deployment..."
        kubectl -n trading set image deployment/cloud-trader \
          cloud-trader=us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/cloud-trader:${BUILD_ID}

        echo "⏳ Waiting for rollout to complete..."
        kubectl -n trading rollout status deployment/cloud-trader --timeout=300s

        echo "✅ Cloud Trader deployment completed successfully"

        # Quick health check
        echo "🏥 Running post-deployment health check..."
        kubectl -n trading get pods -l app=cloud-trader --no-headers | head -3
        kubectl -n trading get ingress --no-headers | head -2

images:
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/cloud-trader:latest'
  - 'us-central1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/cloud-trader:${BUILD_ID}'

options:
  # Balanced performance configuration
  diskSizeGb: 500  # Good balance of speed and cost
  machineType: 'E2_HIGHCPU_32'  # High CPU for faster builds
  # Stable build settings
  dynamicSubstitutions: true
  substitutionOption: 'ALLOW_LOOSE'
  logging: CLOUD_LOGGING_ONLY
  # Reliable buildkit settings
  env:
    - 'DOCKER_BUILDKIT=1'
    - 'BUILDKIT_PROGRESS=plain'

# Conservative timeout for reliability
timeout: '1800s'  # 30 minutes should be sufficient