# ==============================================================================
# Cloud Build CI/CD Pipeline for Sapphire V2
# ==============================================================================

steps:
  # Step 1: Run Tests
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        pip install pytest
        python -m pytest tests/ -v --tb=short
    id: 'test'

  # Step 2: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sapphire-trader:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/sapphire-trader:latest'
      - '.'
    id: 'build'
    waitFor: ['test']

  # Step 3: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/sapphire-trader:$COMMIT_SHA'
    id: 'push-sha'
    waitFor: ['build']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/sapphire-trader:latest'
    id: 'push-latest'
    waitFor: ['build']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sapphire-cloud-trader'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sapphire-trader:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated=false'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'ENVIRONMENT=production'
    id: 'deploy'
    waitFor: ['push-sha']

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/sapphire-trader:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/sapphire-trader:latest'

# Build timeout
timeout: '1200s'

# Substitutions
substitutions:
  _REGION: us-east1

options:
  logging: CLOUD_LOGGING_ONLY
