[profile.default]
src = "contracts"
out = "contracts/out"
libs = ["contracts/lib"]
solc_version = "0.8.20"

[profile.default.rpc_endpoints]
robinhood_testnet = "https://rpc.testnet.chain.robinhood.com"

[etherscan]
robinhood_testnet = { key = "", chain = 46630, url = "https://explorer.testnet.chain.robinhood.com/api" }
