apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplified-trader
  namespace: trading
  labels:
    app: simplified-trader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplified-trader
  template:
    metadata:
      labels:
        app: simplified-trader
    spec:
      containers:
      - name: simplified-trader
        image: us-central1-docker.pkg.dev/sapphireinfinite/cloud-run-source-deploy/cloud-trader:latest
        command: ["uvicorn", "cloud_trader.simplified_api:app", "--host", "0.0.0.0", "--port", "8080"]
        ports:
        - containerPort: 8080
        env:
        - name: TOTAL_CAPITAL
          value: "3500"
        - name: SIMPLIFIED_MODE
          value: "true"
        - name: DISABLE_RATE_LIMITER
          value: "true"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: simplified-trader-service
  namespace: trading
spec:
  selector:
    app: simplified-trader
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
