#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="${PROJECT_ID:-sapphire-479610}"
REGION="${REGION:-us-central1}"
SERVICES="${SERVICES:-sapphire-unified-frontend,sapphire-unified-jobs}"

# Decision / EV knobs
STRATEGY_OPS_GONOGO_MIN_SAMPLE_SIZE="${STRATEGY_OPS_GONOGO_MIN_SAMPLE_SIZE:-30}"
STRATEGY_OPS_GONOGO_MAX_REJECT_TAX_PCT="${STRATEGY_OPS_GONOGO_MAX_REJECT_TAX_PCT:-70}"
STRATEGY_OPS_GONOGO_MAX_HARD_FAIL_PCT="${STRATEGY_OPS_GONOGO_MAX_HARD_FAIL_PCT:-10}"
STRATEGY_OPS_GONOGO_MAX_EV_ERROR_PCT="${STRATEGY_OPS_GONOGO_MAX_EV_ERROR_PCT:-0.35}"
STRATEGY_OPS_GONOGO_MAX_DRAWDOWN_PCT="${STRATEGY_OPS_GONOGO_MAX_DRAWDOWN_PCT:-6.0}"

# Lane scoring knobs
STRATEGY_OPS_FEE_BPS="${STRATEGY_OPS_FEE_BPS:-7.0}"
STRATEGY_OPS_SLIPPAGE_BPS="${STRATEGY_OPS_SLIPPAGE_BPS:-5.0}"
STRATEGY_OPS_DEFAULT_PAYOFF_RATIO="${STRATEGY_OPS_DEFAULT_PAYOFF_RATIO:-1.2}"
STRATEGY_OPS_PROMOTE_MIN_EV_PCT="${STRATEGY_OPS_PROMOTE_MIN_EV_PCT:-0.20}"
STRATEGY_OPS_MONITOR_MIN_EV_PCT="${STRATEGY_OPS_MONITOR_MIN_EV_PCT:-0.05}"
STRATEGY_OPS_DEPRIORITIZE_MAX_EV_PCT="${STRATEGY_OPS_DEPRIORITIZE_MAX_EV_PCT:--0.05}"

ENV_VARS="\
STRATEGY_OPS_GONOGO_MIN_SAMPLE_SIZE=${STRATEGY_OPS_GONOGO_MIN_SAMPLE_SIZE},\
STRATEGY_OPS_GONOGO_MAX_REJECT_TAX_PCT=${STRATEGY_OPS_GONOGO_MAX_REJECT_TAX_PCT},\
STRATEGY_OPS_GONOGO_MAX_HARD_FAIL_PCT=${STRATEGY_OPS_GONOGO_MAX_HARD_FAIL_PCT},\
STRATEGY_OPS_GONOGO_MAX_EV_ERROR_PCT=${STRATEGY_OPS_GONOGO_MAX_EV_ERROR_PCT},\
STRATEGY_OPS_GONOGO_MAX_DRAWDOWN_PCT=${STRATEGY_OPS_GONOGO_MAX_DRAWDOWN_PCT},\
STRATEGY_OPS_FEE_BPS=${STRATEGY_OPS_FEE_BPS},\
STRATEGY_OPS_SLIPPAGE_BPS=${STRATEGY_OPS_SLIPPAGE_BPS},\
STRATEGY_OPS_DEFAULT_PAYOFF_RATIO=${STRATEGY_OPS_DEFAULT_PAYOFF_RATIO},\
STRATEGY_OPS_PROMOTE_MIN_EV_PCT=${STRATEGY_OPS_PROMOTE_MIN_EV_PCT},\
STRATEGY_OPS_MONITOR_MIN_EV_PCT=${STRATEGY_OPS_MONITOR_MIN_EV_PCT},\
STRATEGY_OPS_DEPRIORITIZE_MAX_EV_PCT=${STRATEGY_OPS_DEPRIORITIZE_MAX_EV_PCT}"

IFS=',' read -r -a service_list <<< "$SERVICES"
for svc in "${service_list[@]}"; do
  svc="$(echo "$svc" | xargs)"
  [[ -z "$svc" ]] && continue
  echo "Updating ${svc}..."
  gcloud run services update "$svc" \
    --project "$PROJECT_ID" \
    --region "$REGION" \
    --update-env-vars "$ENV_VARS" >/dev/null
done

echo "Updated services: ${SERVICES}"
