"""Static (offline) analyzer for Pine v5 files.

Catches syntax / contract regressions in `pine/standalone/*.pine` and
committed `pine/generated/` exports BEFORE they merge. Webhook payload
field drift is the highest-cost class of bug here (silent loss of TV
alerts), so the contract checks specifically guard the field names that
`services/webhook/src/receiver.py::TradingViewAlert.from_webhook` reads.

This is NOT a Pine compiler — it's pattern matching. It runs without
the `tv` CLI so it works in CI / pre-commit. For full server-side
validation, use `tv pine check` via the orchestrator (mutation-gated).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any

# Header that marks a file as Sapphire-generated and therefore subject to
# webhook-payload contract checks. Files emitted by `lib.trading.pine_templates`
# (render_sapphire_watch_indicator / _strategy / _screener) carry this header.
SAPPHIRE_HEADER = "// Auto-generated by Sapphire (lib.trading.pine_templates)"

# Required JSON fields per webhook contract (TradingViewAlert.from_webhook).
REQUIRED_PAYLOAD_FIELDS = ("symbol", "action", "price", "time")

# Legacy field name we removed — its presence anywhere in the file is an error.
FORBIDDEN_PAYLOAD_FIELDS = ("ts",)

# Pine has a hard cap on `request.security()` calls per script. Mirrors
# `lib.trading.pine_templates.MAX_SCREENER_SYMBOLS` so the analyzer stays
# decoupled from the generator import path.
MAX_SCREENER_SYMBOLS = 40

# Match top-level indicator(/strategy( call (column 0).
_INDICATOR_RE = re.compile(r"^indicator\s*\(", re.MULTILINE)
_STRATEGY_RE = re.compile(r"^strategy\s*\(", re.MULTILINE)

# Pine alert(...) calls. The payload may concatenate several single-quoted
# string segments via `+`, so we can't just grab one quoted literal. Sapphire-
# generated alerts always pass `alert.freq_*` as the second arg, so we take
# everything between `alert(` and `, alert.freq` (or end-of-line) as the
# payload to inspect for required field names.
_ALERT_RE = re.compile(r"alert\s*\(\s*(?P<payload>.+?)\s*,\s*alert\.freq")

# strategy.entry("Name", ...) / strategy.close("Name") name extraction.
_ENTRY_RE = re.compile(r'strategy\.entry\s*\(\s*"([^"]+)"')
_CLOSE_RE = re.compile(r'strategy\.close\s*\(\s*"([^"]+)"')

# `request.security("SYMBOL", ...)` — used by screener detection +
# tuple-binding validation. The screener generator binds every call to a
# 5-tuple `[long, short, exit_long, exit_short, close]`.
_REQUEST_SECURITY_RE = re.compile(r"request\.security\s*\(")
_TUPLE_BINDING_RE = re.compile(
    r"\[\s*[A-Za-z_][\w,\s]*\s*\]\s*=\s*request\.security\s*\("
)


def _line_of(text: str, idx: int) -> int:
    """Return 1-indexed line number for a character offset."""
    return text.count("\n", 0, idx) + 1


def _check_version(text: str, errors: list[dict[str, Any]]) -> None:
    if "//@version=5" not in text:
        errors.append({"line": 1, "msg": "missing //@version=5 declaration"})


def _check_top_level_call(text: str, errors: list[dict[str, Any]]) -> str | None:
    """Return 'indicator', 'strategy', or None. Push errors as side effect."""
    inds = _INDICATOR_RE.findall(text)
    strats = _STRATEGY_RE.findall(text)
    n = len(inds) + len(strats)
    if n == 0:
        errors.append({"line": 1, "msg": "no top-level indicator(...) or strategy(...) call"})
        return None
    if n > 1:
        errors.append(
            {
                "line": 1,
                "msg": (
                    f"expected exactly one top-level indicator(/strategy( call; "
                    f"found {len(inds)} indicator + {len(strats)} strategy"
                ),
            }
        )
    return "strategy" if strats else "indicator"


def _check_forbidden_fields(text: str, errors: list[dict[str, Any]]) -> None:
    for field in FORBIDDEN_PAYLOAD_FIELDS:
        # Detect "ts": in either single-quoted or escaped double-quote form.
        for match in re.finditer(rf'"{re.escape(field)}"\s*:', text):
            errors.append(
                {
                    "line": _line_of(text, match.start()),
                    "msg": (
                        f'forbidden legacy payload field "{field}"; webhook contract '
                        f"renamed it (see services/webhook/src/receiver.py::"
                        f"TradingViewAlert.from_webhook)"
                    ),
                }
            )


def _check_required_fields_in_alerts(
    text: str, errors: list[dict[str, Any]], warnings: list[dict[str, Any]]
) -> None:
    matches = list(_ALERT_RE.finditer(text))
    if not matches:
        warnings.append(
            {
                "line": 1,
                "msg": "Sapphire-tagged file has no alert(...) calls — nothing to validate",
            }
        )
        return
    for m in matches:
        payload = m.group(1)
        line = _line_of(text, m.start())
        for field in REQUIRED_PAYLOAD_FIELDS:
            # Field name appears as `"<field>":` inside the single-quoted payload.
            if f'"{field}"' not in payload:
                errors.append(
                    {
                        "line": line,
                        "msg": (
                            f'alert payload missing required field "{field}" '
                            f"(webhook contract requires {list(REQUIRED_PAYLOAD_FIELDS)})"
                        ),
                    }
                )


def _check_entry_close_pairing(text: str, warnings: list[dict[str, Any]]) -> None:
    entries = {m.group(1): _line_of(text, m.start()) for m in _ENTRY_RE.finditer(text)}
    closes = {m.group(1) for m in _CLOSE_RE.finditer(text)}
    for name, line in entries.items():
        if name not in closes:
            warnings.append(
                {
                    "line": line,
                    "msg": (
                        f'strategy.entry("{name}", ...) has no matching '
                        f'strategy.close("{name}", ...)'
                    ),
                }
            )


def _check_screener_rules(
    text: str, errors: list[dict[str, Any]], warnings: list[dict[str, Any]]
) -> None:
    """Screener-specific validation (Sapphire-tagged + >1 request.security).

    1. `request.security()` count must not exceed `MAX_SCREENER_SYMBOLS`.
    2. Every `request.security()` call must bind to a tuple — the screener
       contract returns OHLCV-shaped tuples; a bare scalar binding can't
       drive the multi-action alert block.
    3. Alert payloads must NOT use `syminfo.ticker` for the symbol slot —
       that resolves to the chart's ticker, not the firing one, so the
       receiver would route alerts to the wrong symbol.
    """
    sec_calls = list(_REQUEST_SECURITY_RE.finditer(text))
    if len(sec_calls) > MAX_SCREENER_SYMBOLS:
        over_idx = sec_calls[MAX_SCREENER_SYMBOLS].start()
        errors.append(
            {
                "line": _line_of(text, over_idx),
                "msg": (
                    f"screener has {len(sec_calls)} request.security() calls; "
                    f"Pine cap is {MAX_SCREENER_SYMBOLS} "
                    f"(MAX_SCREENER_SYMBOLS in lib.trading.pine_templates)"
                ),
            }
        )

    bindings = list(_TUPLE_BINDING_RE.finditer(text))
    if len(bindings) < len(sec_calls):
        warnings.append(
            {
                "line": _line_of(text, sec_calls[0].start()) if sec_calls else 1,
                "msg": (
                    f"screener has {len(sec_calls)} request.security() calls but only "
                    f"{len(bindings)} tuple bindings — every call must return an "
                    f"OHLCV-shaped tuple"
                ),
            }
        )

    # syminfo.ticker in a screener alert payload silently misroutes alerts
    # to the chart's symbol instead of the firing one.
    for m in _ALERT_RE.finditer(text):
        if "syminfo.ticker" in m.group(1):
            errors.append(
                {
                    "line": _line_of(text, m.start()),
                    "msg": (
                        "screener alert payload uses syminfo.ticker — that resolves "
                        "to the chart's symbol, not the firing symbol; emit the "
                        "request.security'd symbol literal instead"
                    ),
                }
            )


def analyze_pine_source(text: str) -> dict[str, Any]:
    """Run all static checks on a Pine source string.

    Returns: {"ok": bool, "errors": [{line, msg}], "warnings": [{line, msg}]}
    """
    errors: list[dict[str, Any]] = []
    warnings: list[dict[str, Any]] = []

    _check_version(text, errors)
    kind = _check_top_level_call(text, errors)

    is_sapphire = SAPPHIRE_HEADER in text
    if is_sapphire:
        _check_required_fields_in_alerts(text, errors, warnings)

    # Forbidden legacy fields are checked everywhere, not just Sapphire-tagged
    # files — `"ts":` is a regression signal regardless of who authored the file.
    _check_forbidden_fields(text, errors)

    if kind == "strategy":
        _check_entry_close_pairing(text, warnings)

    # Screener-specific rules: only run for Sapphire-tagged sources where
    # multiple `request.security()` calls indicate the multi-symbol screener
    # shape. Hand-authored screeners under `pine/standalone/` are out of scope
    # (no Sapphire tag → no contract).
    if is_sapphire and len(_REQUEST_SECURITY_RE.findall(text)) > 1:
        _check_screener_rules(text, errors, warnings)

    return {"ok": not errors, "errors": errors, "warnings": warnings}


def analyze_pine_file(path: str | Path) -> dict[str, Any]:
    """Convenience wrapper: read `path` and analyze its contents."""
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    result = analyze_pine_source(text)
    result["path"] = str(p)
    return result
