"""Shared definitions to avoid circular imports."""
from dataclasses import dataclass
from typing import Dict, List, Optional, Any

@dataclass
class HealthStatus:
    running: bool
    paper_trading: bool
    last_error: Optional[str]

AGENT_DEFINITIONS: List[Dict[str, Any]] = [
    {
        "id": "trend-momentum-agent",
        "name": "Trend Momentum Agent",
        "model": "gemini-2.0-flash-exp",
        "emoji": "📈",
        "symbols": [],
        "description": "High-speed momentum analysis using Gemini 2.0 Flash Experimental for real-time trend detection and fast execution.",
        "personality": "Aggressive momentum trader, identifies and exploits strong directional moves with lightning-fast execution.",
        "baseline_win_rate": 0.65,
        "risk_multiplier": 1.4,
        "profit_target": 0.008,
        "margin_allocation": 500.0,
        "specialization": "momentum_trading",
        "dynamic_position_sizing": True,
        "adaptive_leverage": True,
        "intelligence_tp_sl": True,
        "max_leverage_limit": 12.0,
        "min_position_size_pct": 0.08,
        "max_position_size_pct": 0.25,
        "risk_tolerance": "high",
        "time_horizon": "very_short",
        "market_regime_preference": "trending",
    },
    {
        "id": "strategy-optimization-agent",
        "name": "Strategy Optimization Agent",
        "model": "gemini-exp-1206",
        "emoji": "🧠",
        "symbols": [],
        "description": "Advanced strategy optimization using Gemini Experimental 1206 for complex analytical reasoning and portfolio optimization.",
        "personality": "Analytical strategist, continuously optimizes trading approaches using advanced reasoning and market analysis.",
        "baseline_win_rate": 0.62,
        "risk_multiplier": 1.6,
        "profit_target": 0.010,
        "margin_allocation": 500.0,
        "specialization": "strategy_optimization",
        "dynamic_position_sizing": True,
        "adaptive_leverage": True,
        "intelligence_tp_sl": True,
        "max_leverage_limit": 10.0,
        "min_position_size_pct": 0.08,
        "max_position_size_pct": 0.22,
        "risk_tolerance": "moderate",
        "time_horizon": "short",
        "market_regime_preference": "all_regimes",
    },
    {
        "id": "financial-sentiment-agent",
        "name": "Financial Sentiment Agent",
        "model": "gemini-2.0-flash-exp",
        "emoji": "💭",
        "symbols": [],
        "description": "Real-time sentiment analysis using Gemini 2.0 Flash Experimental for fast processing of news and social media sentiment.",
        "personality": "Sentiment-focused trader, analyzes market psychology and news impact to identify sentiment-driven opportunities.",
        "baseline_win_rate": 0.58,
        "risk_multiplier": 1.8,
        "profit_target": 0.012,
        "margin_allocation": 500.0,
        "specialization": "sentiment_analysis",
        "dynamic_position_sizing": True,
        "adaptive_leverage": True,
        "intelligence_tp_sl": True,
        "max_leverage_limit": 14.0,
        "min_position_size_pct": 0.08,
        "max_position_size_pct": 0.28,
        "risk_tolerance": "high",
        "time_horizon": "short_medium",
        "market_regime_preference": "news_driven",
    },
    {
        "id": "market-prediction-agent",
        "name": "Market Prediction Agent",
        "model": "gemini-exp-1206",
        "emoji": "🔮",
        "symbols": [],
        "description": "Advanced market prediction using Gemini Experimental 1206 for time series forecasting and macroeconomic analysis.",
        "personality": "Predictive analyst, uses advanced models to forecast market movements and identify high-probability setups.",
        "baseline_win_rate": 0.60,
        "risk_multiplier": 1.7,
        "profit_target": 0.011,
        "margin_allocation": 500.0,
        "specialization": "market_prediction",
        "dynamic_position_sizing": True,
        "adaptive_leverage": True,
        "intelligence_tp_sl": True,
        "max_leverage_limit": 11.0,
        "min_position_size_pct": 0.08,
        "max_position_size_pct": 0.24,
        "risk_tolerance": "moderate_high",
        "time_horizon": "medium",
        "market_regime_preference": "predictable",
    },
    {
        "id": "volume-microstructure-agent",
        "name": "Volume Microstructure Agent",
        "model": "codey-001",
        "emoji": "📊",
        "symbols": [],
        "description": "Mathematical volume analysis using Codey for precise order flow and microstructure analysis.",
        "personality": "Quantitative analyst, focuses on order book dynamics and institutional activity patterns.",
        "baseline_win_rate": 0.55,
        "risk_multiplier": 2.0,
        "profit_target": 0.006,
        "margin_allocation": 500.0,
        "specialization": "volume_analysis",
        "dynamic_position_sizing": True,
        "adaptive_leverage": True,
        "intelligence_tp_sl": True,
        "max_leverage_limit": 16.0,
        "min_position_size_pct": 0.08,
        "max_position_size_pct": 0.20,
        "risk_tolerance": "high",
        "time_horizon": "very_short",
        "market_regime_preference": "liquid",
    },
    {
        "id": "vpin-hft",
        "name": "VPIN HFT Agent",
        "model": "gemini-2.0-flash-exp",
        "emoji": "⚡",
        "symbols": [],
        "description": "High-frequency trading agent using Gemini 2.0 Flash Experimental for real-time order flow toxicity detection and volume microstructure analysis to predict short-term price movements.",
        "personality": "Aggressive, high-frequency, AI-powered pattern recognition in market microstructure.",
        "baseline_win_rate": 0.55,
        "risk_multiplier": 3.0,
        "profit_target": 0.005,
        "margin_allocation": 500.0,
        "specialization": "volume_hft",
        "dynamic_position_sizing": True,
        "adaptive_leverage": True,
        "intelligence_tp_sl": True,
        "max_leverage_limit": 30.0,
        "min_position_size_pct": 0.08,
        "max_position_size_pct": 0.10,
        "risk_tolerance": "very_high",
        "time_horizon": "very_short",
        "market_regime_preference": "volatile",
    },
]
