#!/usr/bin/env bash
set -euo pipefail

# Deploy a named strategy profile to the rari2 Lighter bot (.env + restart).
# Usage:
#   scripts/deploy_lighter_strategy_profile.sh [profile] [host]
#
# Profiles:
#   luxalgo_sol_15m_safe    (default)
#   luxalgo_sol_5m_active
#   chartprime_sol_5m_test
#   chartprime_sol_15m_walkforward_safe
#   luxalgo_sol_1h_walkforward_safe
#   overnight_exploration
#   failover_canary_only

PROFILE="${1:-luxalgo_sol_15m_safe}"
TARGET_HOST="${2:-rari@100.87.225.89}"
ENV_FILE="/home/rari/Sapphire/services/bot-lighter/.env"
SERVICE="lighter-trading"

declare -A KV

case "$PROFILE" in
  luxalgo_sol_15m_safe)
    KV[LIGHTER_ALLOWED_STRATEGIES]="luxalgo_msb_ob,smart_money_breakout,algoalpha_smb"
    KV[LIGHTER_ALLOWED_TIMEFRAMES]="15m"
    KV[LIGHTER_STRATEGY_REQUIRE_METADATA]="true"
    KV[LIGHTER_SINGLE_SYMBOL_MODE]="true"
    KV[LIGHTER_MAX_ORDER_NOTIONAL_USD]="4"
    KV[LIGHTER_MAX_POSITION_NOTIONAL_USD]="4"
    KV[LIGHTER_TARGET_ORDER_NOTIONAL_USD]="4"
    KV[LIGHTER_MIN_ENTRY_NOTIONAL_USD]="3.5"
    KV[LIGHTER_MAX_SIGNAL_LEVERAGE]="20"
    KV[LIGHTER_SYNC_BEFORE_ENTRY]="true"
    KV[LIGHTER_JURISDICTION_BLOCK_SECONDS]="900"
    KV[LIGHTER_ENTRY_COOLDOWN_SECONDS]="600"
    KV[LIGHTER_DEFAULT_TAKE_PROFIT_PCT]="1.2"
    KV[LIGHTER_DEFAULT_STOP_LOSS_PCT]="0.8"
    KV[LIGHTER_PROGRESS_VERIFY_INTERVAL_SECONDS]="120"
    KV[LIGHTER_POSITION_CHECK_INTERVAL_SECONDS]="5"
    KV[LIGHTER_MAX_DRAWDOWN_ALERT_PCT]="6"
    KV[LIGHTER_DRAWDOWN_ALERT_COOLDOWN_SECONDS]="900"
    KV[LIGHTER_SYNC_STALE_ALERT_SECONDS]="300"
    KV[LIGHTER_SYNC_STALE_ALERT_COOLDOWN_SECONDS]="900"
    KV[LIGHTER_MAX_POSITION_HOLD_SECONDS]="7200"
    ;;
  luxalgo_sol_5m_active)
    KV[LIGHTER_ALLOWED_STRATEGIES]="luxalgo_msb_ob,smart_money_breakout,algoalpha_smb"
    KV[LIGHTER_ALLOWED_TIMEFRAMES]="5m"
    KV[LIGHTER_STRATEGY_REQUIRE_METADATA]="true"
    KV[LIGHTER_SINGLE_SYMBOL_MODE]="true"
    KV[LIGHTER_MAX_ORDER_NOTIONAL_USD]="4"
    KV[LIGHTER_MAX_POSITION_NOTIONAL_USD]="4"
    KV[LIGHTER_TARGET_ORDER_NOTIONAL_USD]="4"
    KV[LIGHTER_MIN_ENTRY_NOTIONAL_USD]="3.5"
    KV[LIGHTER_MAX_SIGNAL_LEVERAGE]="20"
    KV[LIGHTER_SYNC_BEFORE_ENTRY]="true"
    KV[LIGHTER_JURISDICTION_BLOCK_SECONDS]="900"
    KV[LIGHTER_ENTRY_COOLDOWN_SECONDS]="180"
    KV[LIGHTER_DEFAULT_TAKE_PROFIT_PCT]="1.2"
    KV[LIGHTER_DEFAULT_STOP_LOSS_PCT]="0.8"
    KV[LIGHTER_PROGRESS_VERIFY_INTERVAL_SECONDS]="120"
    KV[LIGHTER_POSITION_CHECK_INTERVAL_SECONDS]="5"
    KV[LIGHTER_MAX_DRAWDOWN_ALERT_PCT]="7"
    KV[LIGHTER_DRAWDOWN_ALERT_COOLDOWN_SECONDS]="900"
    KV[LIGHTER_SYNC_STALE_ALERT_SECONDS]="300"
    KV[LIGHTER_SYNC_STALE_ALERT_COOLDOWN_SECONDS]="900"
    KV[LIGHTER_MAX_POSITION_HOLD_SECONDS]="3600"
    ;;
  chartprime_sol_5m_test)
    KV[LIGHTER_ALLOWED_STRATEGIES]="chartprime_tbt,trendline_breakout_targets"
    KV[LIGHTER_ALLOWED_TIMEFRAMES]="5m"
    KV[LIGHTER_STRATEGY_REQUIRE_METADATA]="true"
    KV[LIGHTER_SINGLE_SYMBOL_MODE]="true"
    KV[LIGHTER_MAX_ORDER_NOTIONAL_USD]="4"
    KV[LIGHTER_MAX_POSITION_NOTIONAL_USD]="4"
    KV[LIGHTER_TARGET_ORDER_NOTIONAL_USD]="4"
    KV[LIGHTER_MIN_ENTRY_NOTIONAL_USD]="3.5"
    KV[LIGHTER_MAX_SIGNAL_LEVERAGE]="20"
    KV[LIGHTER_SYNC_BEFORE_ENTRY]="true"
    KV[LIGHTER_JURISDICTION_BLOCK_SECONDS]="900"
    KV[LIGHTER_ENTRY_COOLDOWN_SECONDS]="300"
    KV[LIGHTER_DEFAULT_TAKE_PROFIT_PCT]="1.0"
    KV[LIGHTER_DEFAULT_STOP_LOSS_PCT]="0.7"
    KV[LIGHTER_PROGRESS_VERIFY_INTERVAL_SECONDS]="120"
    KV[LIGHTER_POSITION_CHECK_INTERVAL_SECONDS]="5"
    KV[LIGHTER_MAX_DRAWDOWN_ALERT_PCT]="5"
    KV[LIGHTER_DRAWDOWN_ALERT_COOLDOWN_SECONDS]="900"
    KV[LIGHTER_SYNC_STALE_ALERT_SECONDS]="300"
    KV[LIGHTER_SYNC_STALE_ALERT_COOLDOWN_SECONDS]="900"
    KV[LIGHTER_MAX_POSITION_HOLD_SECONDS]="3600"
    ;;
  chartprime_sol_15m_walkforward_safe)
    KV[LIGHTER_ALLOWED_STRATEGIES]="chartprime_tbt,trendline_breakout_targets"
    KV[LIGHTER_ALLOWED_TIMEFRAMES]="15m"
    KV[LIGHTER_STRATEGY_REQUIRE_METADATA]="true"
    KV[LIGHTER_SINGLE_SYMBOL_MODE]="true"
    KV[LIGHTER_MAX_ORDER_NOTIONAL_USD]="4"
    KV[LIGHTER_MAX_POSITION_NOTIONAL_USD]="4"
    KV[LIGHTER_TARGET_ORDER_NOTIONAL_USD]="4"
    KV[LIGHTER_MIN_ENTRY_NOTIONAL_USD]="3.5"
    KV[LIGHTER_MAX_SIGNAL_LEVERAGE]="3"
    KV[LIGHTER_SYNC_BEFORE_ENTRY]="true"
    KV[LIGHTER_JURISDICTION_BLOCK_SECONDS]="900"
    KV[LIGHTER_ENTRY_COOLDOWN_SECONDS]="3600"
    KV[LIGHTER_DEFAULT_TAKE_PROFIT_PCT]="1.0"
    KV[LIGHTER_DEFAULT_STOP_LOSS_PCT]="0.7"
    KV[LIGHTER_PROGRESS_VERIFY_INTERVAL_SECONDS]="120"
    KV[LIGHTER_POSITION_CHECK_INTERVAL_SECONDS]="5"
    KV[LIGHTER_MAX_DRAWDOWN_ALERT_PCT]="4"
    KV[LIGHTER_DRAWDOWN_ALERT_COOLDOWN_SECONDS]="900"
    KV[LIGHTER_SYNC_STALE_ALERT_SECONDS]="300"
    KV[LIGHTER_SYNC_STALE_ALERT_COOLDOWN_SECONDS]="900"
    KV[LIGHTER_MAX_POSITION_HOLD_SECONDS]="5400"
    ;;
  luxalgo_sol_1h_walkforward_safe)
    KV[LIGHTER_ALLOWED_STRATEGIES]="luxalgo_msb_ob,smart_money_breakout,algoalpha_smb"
    KV[LIGHTER_ALLOWED_TIMEFRAMES]="1h"
    KV[LIGHTER_STRATEGY_REQUIRE_METADATA]="true"
    KV[LIGHTER_SINGLE_SYMBOL_MODE]="true"
    KV[LIGHTER_MAX_ORDER_NOTIONAL_USD]="4"
    KV[LIGHTER_MAX_POSITION_NOTIONAL_USD]="4"
    KV[LIGHTER_TARGET_ORDER_NOTIONAL_USD]="4"
    KV[LIGHTER_MIN_ENTRY_NOTIONAL_USD]="3.5"
    KV[LIGHTER_MAX_SIGNAL_LEVERAGE]="3"
    KV[LIGHTER_SYNC_BEFORE_ENTRY]="true"
    KV[LIGHTER_JURISDICTION_BLOCK_SECONDS]="900"
    KV[LIGHTER_ENTRY_COOLDOWN_SECONDS]="7200"
    KV[LIGHTER_DEFAULT_TAKE_PROFIT_PCT]="1.2"
    KV[LIGHTER_DEFAULT_STOP_LOSS_PCT]="0.8"
    KV[LIGHTER_PROGRESS_VERIFY_INTERVAL_SECONDS]="120"
    KV[LIGHTER_POSITION_CHECK_INTERVAL_SECONDS]="5"
    KV[LIGHTER_MAX_DRAWDOWN_ALERT_PCT]="4"
    KV[LIGHTER_DRAWDOWN_ALERT_COOLDOWN_SECONDS]="900"
    KV[LIGHTER_SYNC_STALE_ALERT_SECONDS]="300"
    KV[LIGHTER_SYNC_STALE_ALERT_COOLDOWN_SECONDS]="900"
    KV[LIGHTER_MAX_POSITION_HOLD_SECONDS]="5400"
    ;;
  overnight_exploration)
    KV[TRADING_ENABLED]="1"
    KV[ALLOW_LIVE_TRADING]="1"
    KV[LIGHTER_ALLOWED_STRATEGIES]="overnight_ema_crossover"
    KV[LIGHTER_ALLOWED_TIMEFRAMES]="5m"
    KV[LIGHTER_STRATEGY_REQUIRE_METADATA]="true"
    KV[LIGHTER_SINGLE_SYMBOL_MODE]="true"
    KV[LIGHTER_MAX_ORDER_NOTIONAL_USD]="4"
    KV[LIGHTER_MAX_POSITION_NOTIONAL_USD]="4"
    KV[LIGHTER_MAX_PORTFOLIO_NOTIONAL_USD]="4"
    KV[LIGHTER_TARGET_ORDER_NOTIONAL_USD]="4"
    KV[LIGHTER_MIN_ENTRY_NOTIONAL_USD]="2.0"
    KV[LIGHTER_MAX_SIGNAL_LEVERAGE]="20"
    KV[LIGHTER_SYNC_BEFORE_ENTRY]="true"
    KV[LIGHTER_JURISDICTION_BLOCK_SECONDS]="900"
    KV[LIGHTER_ENTRY_COOLDOWN_SECONDS]="120"
    KV[LIGHTER_DEFAULT_TAKE_PROFIT_PCT]="1.4"
    KV[LIGHTER_DEFAULT_STOP_LOSS_PCT]="0.9"
    KV[LIGHTER_PROGRESS_VERIFY_INTERVAL_SECONDS]="120"
    KV[LIGHTER_POSITION_CHECK_INTERVAL_SECONDS]="5"
    KV[LIGHTER_MAX_DRAWDOWN_ALERT_PCT]="8"
    KV[LIGHTER_DRAWDOWN_ALERT_COOLDOWN_SECONDS]="900"
    KV[LIGHTER_SYNC_STALE_ALERT_SECONDS]="300"
    KV[LIGHTER_SYNC_STALE_ALERT_COOLDOWN_SECONDS]="900"
    KV[LIGHTER_MAX_POSITION_HOLD_SECONDS]="1200"
    KV[LIGHTER_DYNAMIC_SIZING_ENABLED]="true"
    KV[LIGHTER_DYNAMIC_SIZE_MIN_MULT]="0.35"
    KV[LIGHTER_DYNAMIC_SIZE_MAX_MULT]="1.15"
    KV[LIGHTER_OPPORTUNITY_ROTATION_ENABLED]="true"
    KV[LIGHTER_OPPORTUNITY_MIN_EDGE_PCT]="0.20"
    KV[LIGHTER_OPPORTUNITY_COOLDOWN_SECONDS]="120"
    ;;
  failover_canary_only)
    KV[TRADING_ENABLED]="1"
    KV[ALLOW_LIVE_TRADING]="1"
    KV[LIGHTER_ALLOWED_STRATEGIES]="luxalgo_msb_ob,smart_money_breakout,algoalpha_smb"
    KV[LIGHTER_ALLOWED_TIMEFRAMES]="5m"
    KV[LIGHTER_ALLOWED_SIGNAL_SOURCES]="codex-unified-prod-test,sapphirectl-canary"
    KV[LIGHTER_STRATEGY_REQUIRE_METADATA]="true"
    KV[LIGHTER_SINGLE_SYMBOL_MODE]="true"
    KV[LIGHTER_MAX_ORDER_NOTIONAL_USD]="1.5"
    KV[LIGHTER_MAX_POSITION_NOTIONAL_USD]="2.0"
    KV[LIGHTER_TARGET_ORDER_NOTIONAL_USD]="1.0"
    KV[LIGHTER_MIN_ENTRY_NOTIONAL_USD]="0.5"
    KV[LIGHTER_MAX_SIGNAL_LEVERAGE]="3"
    KV[LIGHTER_SYNC_BEFORE_ENTRY]="true"
    KV[LIGHTER_JURISDICTION_BLOCK_SECONDS]="900"
    KV[LIGHTER_ENTRY_COOLDOWN_SECONDS]="120"
    KV[LIGHTER_DEFAULT_TAKE_PROFIT_PCT]="1.0"
    KV[LIGHTER_DEFAULT_STOP_LOSS_PCT]="0.7"
    KV[LIGHTER_PROGRESS_VERIFY_INTERVAL_SECONDS]="120"
    KV[LIGHTER_POSITION_CHECK_INTERVAL_SECONDS]="5"
    KV[LIGHTER_MAX_DRAWDOWN_ALERT_PCT]="4"
    KV[LIGHTER_DRAWDOWN_ALERT_COOLDOWN_SECONDS]="900"
    KV[LIGHTER_SYNC_STALE_ALERT_SECONDS]="300"
    KV[LIGHTER_SYNC_STALE_ALERT_COOLDOWN_SECONDS]="900"
    KV[LIGHTER_MAX_POSITION_HOLD_SECONDS]="1800"
    ;;
  *)
    echo "Unknown profile: $PROFILE" >&2
    exit 1
    ;;
esac

# Global operational defaults (applies unless profile explicitly overrides).
: "${KV[LIGHTER_EXECUTION_WATCHDOG_ENABLED]:=true}"
: "${KV[LIGHTER_EXECUTION_WATCHDOG_NO_FILL_SECONDS]:=900}"
: "${KV[LIGHTER_EXECUTION_WATCHDOG_COOLDOWN_SECONDS]:=900}"
: "${KV[LIGHTER_EXECUTION_FAILSAFE_ENABLED]:=true}"
: "${KV[LIGHTER_EXECUTION_FAILSAFE_ALERT_THRESHOLD]:=3}"
: "${KV[LIGHTER_EXECUTION_FAILSAFE_HOLD_SECONDS]:=1800}"
: "${KV[LIGHTER_DYNAMIC_SIZING_ENABLED]:=true}"
: "${KV[LIGHTER_DYNAMIC_SIZE_MIN_MULT]:=0.35}"
: "${KV[LIGHTER_DYNAMIC_SIZE_MAX_MULT]:=1.20}"
: "${KV[LIGHTER_LANE_HEARTBEAT_ENABLED]:=true}"
: "${KV[LIGHTER_LANE_HEARTBEAT_SECONDS]:=900}"

echo "Applying profile '$PROFILE' to $TARGET_HOST ..."

# Build Python dict literal content safely.
UPDATES_PY=""
for k in "${!KV[@]}"; do
  v="${KV[$k]}"
  UPDATES_PY="${UPDATES_PY}    '${k}': '${v}',"$'\n'
done

ssh -o BatchMode=yes -o ConnectTimeout=10 "$TARGET_HOST" "python3 - <<'PY'
from pathlib import Path

env_file = Path('${ENV_FILE}')
lines = env_file.read_text().splitlines() if env_file.exists() else []
updates = {
${UPDATES_PY}}

out = []
seen = set()
for ln in lines:
    if '=' in ln and not ln.strip().startswith('#'):
        key, _ = ln.split('=', 1)
        k = key.strip()
        if k in updates:
            out.append(f\"{k}={updates[k]}\")
            seen.add(k)
            continue
    out.append(ln)

for k, v in updates.items():
    if k not in seen:
        out.append(f\"{k}={v}\")

env_file.write_text('\\n'.join(out) + '\\n')
print(f'Updated {env_file}')
for k in sorted(updates):
    print(f'{k}={updates[k]}')
PY"

ssh -o BatchMode=yes -o ConnectTimeout=10 "$TARGET_HOST" \
  "sudo systemctl reset-failed ${SERVICE} || true; \
   timeout 30s sudo systemctl restart ${SERVICE} || { \
     sudo systemctl reset-failed ${SERVICE} || true; \
     timeout 20s sudo systemctl stop ${SERVICE} || true; \
     sudo pkill -f 'services/bot-lighter/src/main.py' || true; \
     sudo systemctl start ${SERVICE}; \
   }; \
   sleep 8; \
   systemctl is-active ${SERVICE}; \
   journalctl -u ${SERVICE} -n 50 --no-pager"

echo
echo "Profile '${PROFILE}' deployed."
