#!/usr/bin/env bash
# Build and deploy sapphire-alpha control plane.

set -euo pipefail

PROJECT_ID="${PROJECT_ID:-sapphire-479610}"
REGION="${REGION:-us-central1}"
AR_REGION="${AR_REGION:-northamerica-northeast1}"
AR_REPO="${AR_REPO:-sapphire-repo}"
SERVICE_NAME="${SERVICE_NAME:-sapphire-alpha}"
IMAGE_NAME="${IMAGE_NAME:-sapphire-alpha}"
IMAGE_TAG="${IMAGE_TAG:-$(date -u +%Y%m%d%H%M)-alpha}"
PLATFORM="${PLATFORM:-linux/amd64}"
CPU="${CPU:-1}"
MEMORY="${MEMORY:-1Gi}"
CONCURRENCY="${CONCURRENCY:-80}"
TIMEOUT="${TIMEOUT:-300}"
PORT="${PORT:-8080}"
SERVICE_ACCOUNT="${SERVICE_ACCOUNT:-sapphire-main-sa@${PROJECT_ID}.iam.gserviceaccount.com}"
FULL_AUTONOMY_ENABLED="${FULL_AUTONOMY_ENABLED:-true}"
AUTONOMY_ALLOW_CODE_CHANGES="${AUTONOMY_ALLOW_CODE_CHANGES:-true}"
AUTONOMY_ALLOW_GCLOUD_CHANGES="${AUTONOMY_ALLOW_GCLOUD_CHANGES:-true}"
AUTONOMY_DRY_RUN="${AUTONOMY_DRY_RUN:-false}"
AUTONOMY_REQUIRE_OWNER_APPROVAL="${AUTONOMY_REQUIRE_OWNER_APPROVAL:-false}"
AUTONOMY_LOOP_SECONDS="${AUTONOMY_LOOP_SECONDS:-900}"
AUTONOMY_MIN_DISPATCH_INTERVAL_SECONDS="${AUTONOMY_MIN_DISPATCH_INTERVAL_SECONDS:-600}"
GEMINI_FLASH_MIN_INTERVAL_SECONDS="${GEMINI_FLASH_MIN_INTERVAL_SECONDS:-1800}"
TRADINGVIEW_EXECUTION_ENABLED="${TRADINGVIEW_EXECUTION_ENABLED:-false}"
TRADINGVIEW_DEFAULT_QUANTITY="${TRADINGVIEW_DEFAULT_QUANTITY:-0.02}"
TRADINGVIEW_ENFORCE_STRATEGY_RULES="${TRADINGVIEW_ENFORCE_STRATEGY_RULES:-false}"
TRADINGVIEW_AUTONOMY_ENABLED="${TRADINGVIEW_AUTONOMY_ENABLED:-true}"
TRADINGVIEW_AUTONOMY_ALLOW_MUTATIONS="${TRADINGVIEW_AUTONOMY_ALLOW_MUTATIONS:-true}"
TRADINGVIEW_ALLOW_ALL_ASSETS="${TRADINGVIEW_ALLOW_ALL_ASSETS:-true}"
TRADINGVIEW_COMMUNITY_ACCESS_ENABLED="${TRADINGVIEW_COMMUNITY_ACCESS_ENABLED:-true}"
TRADINGVIEW_AUTONOMY_HOOK_URL="${TRADINGVIEW_AUTONOMY_HOOK_URL:-https://sapphire-gateway-s77j6bxyra-uc.a.run.app/hooks/agent}"
TRADINGVIEW_AUTONOMY_AGENT_ID="${TRADINGVIEW_AUTONOMY_AGENT_ID:-sapphire}"
TRADINGVIEW_IDEMPOTENCY_WINDOW_SECONDS="${TRADINGVIEW_IDEMPOTENCY_WINDOW_SECONDS:-300}"
TRADINGVIEW_IDEMPOTENCY_MAX_KEYS="${TRADINGVIEW_IDEMPOTENCY_MAX_KEYS:-2000}"
TRADINGVIEW_MAX_QUANTITY_ASTER="${TRADINGVIEW_MAX_QUANTITY_ASTER:-0.25}"
TRADINGVIEW_MAX_QUANTITY_LIGHTER="${TRADINGVIEW_MAX_QUANTITY_LIGHTER:-0.25}"
TRADINGVIEW_ALLOWED_SYMBOLS_ASTER="${TRADINGVIEW_ALLOWED_SYMBOLS_ASTER:-SOL;JUP;PYTH;BONK;WIF}"
TRADINGVIEW_ALLOWED_SYMBOLS_LIGHTER="${TRADINGVIEW_ALLOWED_SYMBOLS_LIGHTER:-BTC;ETH;SOL;HYPE;DOGE;AVAX}"
ENABLED_VENUES="${ENABLED_VENUES:-ASTER;LIGHTER}"
BOT_ASTER_URL="${BOT_ASTER_URL:-https://sapphire-aster-267358751314.us-central1.run.app}"
BOT_LIGHTER_URL="${BOT_LIGHTER_URL:-https://sapphire-lighter-267358751314.europe-west1.run.app}"
TELEGRAM_HEARTBEAT_INTERVAL_SECONDS="${TELEGRAM_HEARTBEAT_INTERVAL_SECONDS:-900}"
TELEGRAM_WEBHOOK_URL="${TELEGRAM_WEBHOOK_URL:-https://sapphire-alpha-267358751314.us-central1.run.app/telegram/webhook}"
INTERNAL_ARB_EXECUTION_ENABLED="${INTERNAL_ARB_EXECUTION_ENABLED:-false}"
INTERNAL_ARB_EXECUTION_QUANTITY="${INTERNAL_ARB_EXECUTION_QUANTITY:-0.02}"
GCP_PROJECT_ID_ENV="${GCP_PROJECT_ID_ENV:-${PROJECT_ID}}"
SERVICE_NAME_ENV="${SERVICE_NAME_ENV:-alpha-engine}"
PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
SAPPHIRE_ALLOWED_REPOS="${SAPPHIRE_ALLOWED_REPOS:-arigatoexpress/Sapphire;Sapphire}"
SAPPHIRE_ALLOWED_GCP_PROJECTS="${SAPPHIRE_ALLOWED_GCP_PROJECTS:-${PROJECT_ID}}"
SAPPHIRE_BLOCKED_SCOPE_TERMS="${SAPPHIRE_BLOCKED_SCOPE_TERMS:-sapphireai;sapphire-inc;sapphire_inc}"
SAPPHIRE_SCOUT_AGENT_ID="${SAPPHIRE_SCOUT_AGENT_ID:-SAPPHIRE_SCOUT}"
SAPPHIRE_SCOUT_DISPATCH_AGENT_ID="${SAPPHIRE_SCOUT_DISPATCH_AGENT_ID:-sapphire}"
SAPPHIRE_SCOUT_OPENCLAW_CHAT_ID="${SAPPHIRE_SCOUT_OPENCLAW_CHAT_ID:-${TELEGRAM_CHAT_ID:-}}"
SAPPHIRE_SCOUT_OPENCLAW_HOOK_URL="${SAPPHIRE_SCOUT_OPENCLAW_HOOK_URL:-${TRADINGVIEW_AUTONOMY_HOOK_URL}}"
SCOUT_REGISTER_URL_SECRET="${SCOUT_REGISTER_URL_SECRET:-SAPPHIRE_SCOUT_EXTERNAL_REGISTER_URL}"
SCOUT_POST_URL_SECRET="${SCOUT_POST_URL_SECRET:-SAPPHIRE_SCOUT_EXTERNAL_POST_URL}"
SCOUT_API_TOKEN_SECRET="${SCOUT_API_TOKEN_SECRET:-SAPPHIRE_SCOUT_EXTERNAL_API_TOKEN}"
SAPPHIRE_VT_ENABLED="${SAPPHIRE_VT_ENABLED:-true}"
SAPPHIRE_VT_ENFORCEMENT_MODE="${SAPPHIRE_VT_ENFORCEMENT_MODE:-block_malicious}"
SAPPHIRE_VT_UPLOAD_IF_MISSING="${SAPPHIRE_VT_UPLOAD_IF_MISSING:-true}"
SAPPHIRE_VT_MAX_POLL_ATTEMPTS="${SAPPHIRE_VT_MAX_POLL_ATTEMPTS:-12}"
SAPPHIRE_VT_POLL_INTERVAL_SECONDS="${SAPPHIRE_VT_POLL_INTERVAL_SECONDS:-5}"
VIRUSTOTAL_API_KEY_SECRET="${VIRUSTOTAL_API_KEY_SECRET:-VIRUSTOTAL_API_KEY}"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ALPHA_DIR="${ROOT_DIR}/services/alpha-engine"
IMAGE_URI="${AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPO}/${IMAGE_NAME}:${IMAGE_TAG}"
IMAGE_LATEST="${AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPO}/${IMAGE_NAME}:latest"

has_secret() {
  local name="$1"
  gcloud secrets describe "${name}" --project "${PROJECT_ID}" >/dev/null 2>&1
}

echo "== Sapphire Alpha Deploy =="
echo "Project: ${PROJECT_ID}"
echo "Region: ${REGION}"
echo "Image: ${IMAGE_URI}"
echo

docker buildx build \
  --platform "${PLATFORM}" \
  -f "${ALPHA_DIR}/Dockerfile" \
  -t "${IMAGE_URI}" \
  -t "${IMAGE_LATEST}" \
  --push "${ROOT_DIR}"

gcloud run deploy "${SERVICE_NAME}" \
  --project "${PROJECT_ID}" \
  --region "${REGION}" \
  --image "${IMAGE_URI}" \
  --platform managed \
  --allow-unauthenticated \
  --service-account "${SERVICE_ACCOUNT}" \
  --memory "${MEMORY}" \
  --cpu "${CPU}" \
  --concurrency "${CONCURRENCY}" \
  --timeout "${TIMEOUT}" \
  --port "${PORT}" \
  --update-env-vars "GCP_PROJECT_ID=${GCP_PROJECT_ID_ENV}" \
  --update-env-vars "SERVICE_NAME=${SERVICE_NAME_ENV}" \
  --update-env-vars "PYTHONUNBUFFERED=${PYTHONUNBUFFERED}" \
  --update-env-vars "ENABLED_VENUES=${ENABLED_VENUES}" \
  --update-env-vars "BOT_ASTER_URL=${BOT_ASTER_URL}" \
  --update-env-vars "BOT_LIGHTER_URL=${BOT_LIGHTER_URL}" \
  --update-env-vars "TELEGRAM_HEARTBEAT_INTERVAL_SECONDS=${TELEGRAM_HEARTBEAT_INTERVAL_SECONDS}" \
  --update-env-vars "TELEGRAM_WEBHOOK_URL=${TELEGRAM_WEBHOOK_URL}" \
  --update-env-vars "TRADINGVIEW_IDEMPOTENCY_WINDOW_SECONDS=${TRADINGVIEW_IDEMPOTENCY_WINDOW_SECONDS}" \
  --update-env-vars "TRADINGVIEW_IDEMPOTENCY_MAX_KEYS=${TRADINGVIEW_IDEMPOTENCY_MAX_KEYS}" \
  --update-env-vars "TRADINGVIEW_MAX_QUANTITY_ASTER=${TRADINGVIEW_MAX_QUANTITY_ASTER}" \
  --update-env-vars "TRADINGVIEW_MAX_QUANTITY_LIGHTER=${TRADINGVIEW_MAX_QUANTITY_LIGHTER}" \
  --update-env-vars "TRADINGVIEW_ALLOWED_SYMBOLS_ASTER=${TRADINGVIEW_ALLOWED_SYMBOLS_ASTER}" \
  --update-env-vars "TRADINGVIEW_ALLOWED_SYMBOLS_LIGHTER=${TRADINGVIEW_ALLOWED_SYMBOLS_LIGHTER}" \
  --update-env-vars "TRADINGVIEW_ENFORCE_STRATEGY_RULES=${TRADINGVIEW_ENFORCE_STRATEGY_RULES}" \
  --update-env-vars "TRADINGVIEW_AUTONOMY_ENABLED=${TRADINGVIEW_AUTONOMY_ENABLED}" \
  --update-env-vars "TRADINGVIEW_AUTONOMY_ALLOW_MUTATIONS=${TRADINGVIEW_AUTONOMY_ALLOW_MUTATIONS}" \
  --update-env-vars "TRADINGVIEW_ALLOW_ALL_ASSETS=${TRADINGVIEW_ALLOW_ALL_ASSETS}" \
  --update-env-vars "TRADINGVIEW_COMMUNITY_ACCESS_ENABLED=${TRADINGVIEW_COMMUNITY_ACCESS_ENABLED}" \
  --update-env-vars "TRADINGVIEW_AUTONOMY_HOOK_URL=${TRADINGVIEW_AUTONOMY_HOOK_URL}" \
  --update-env-vars "TRADINGVIEW_AUTONOMY_AGENT_ID=${TRADINGVIEW_AUTONOMY_AGENT_ID}" \
  --update-env-vars "INTERNAL_ARB_EXECUTION_ENABLED=${INTERNAL_ARB_EXECUTION_ENABLED}" \
  --update-env-vars "INTERNAL_ARB_EXECUTION_QUANTITY=${INTERNAL_ARB_EXECUTION_QUANTITY}" \
  --update-env-vars "SAPPHIRE_FULL_AUTONOMY_ENABLED=${FULL_AUTONOMY_ENABLED}" \
  --update-env-vars "SAPPHIRE_AUTONOMY_ALLOW_CODE_CHANGES=${AUTONOMY_ALLOW_CODE_CHANGES}" \
  --update-env-vars "SAPPHIRE_AUTONOMY_ALLOW_GCLOUD_CHANGES=${AUTONOMY_ALLOW_GCLOUD_CHANGES}" \
  --update-env-vars "SAPPHIRE_AUTONOMY_DRY_RUN=${AUTONOMY_DRY_RUN}" \
  --update-env-vars "SAPPHIRE_AUTONOMY_REQUIRE_OWNER_APPROVAL=${AUTONOMY_REQUIRE_OWNER_APPROVAL}" \
  --update-env-vars "SAPPHIRE_AUTONOMY_LOOP_SECONDS=${AUTONOMY_LOOP_SECONDS}" \
  --update-env-vars "SAPPHIRE_AUTONOMY_MIN_DISPATCH_INTERVAL_SECONDS=${AUTONOMY_MIN_DISPATCH_INTERVAL_SECONDS}" \
  --update-env-vars "GEMINI_FLASH_MIN_INTERVAL_SECONDS=${GEMINI_FLASH_MIN_INTERVAL_SECONDS}" \
  --update-env-vars "TRADINGVIEW_EXECUTION_ENABLED=${TRADINGVIEW_EXECUTION_ENABLED}" \
  --update-env-vars "TRADINGVIEW_DEFAULT_QUANTITY=${TRADINGVIEW_DEFAULT_QUANTITY}" \
  --update-env-vars "SAPPHIRE_ALLOWED_REPOS=${SAPPHIRE_ALLOWED_REPOS}" \
  --update-env-vars "SAPPHIRE_ALLOWED_GCP_PROJECTS=${SAPPHIRE_ALLOWED_GCP_PROJECTS}" \
  --update-env-vars "SAPPHIRE_BLOCKED_SCOPE_TERMS=${SAPPHIRE_BLOCKED_SCOPE_TERMS}" \
  --update-env-vars "SAPPHIRE_VT_ENABLED=${SAPPHIRE_VT_ENABLED}" \
  --update-env-vars "SAPPHIRE_VT_ENFORCEMENT_MODE=${SAPPHIRE_VT_ENFORCEMENT_MODE}" \
  --update-env-vars "SAPPHIRE_VT_UPLOAD_IF_MISSING=${SAPPHIRE_VT_UPLOAD_IF_MISSING}" \
  --update-env-vars "SAPPHIRE_VT_MAX_POLL_ATTEMPTS=${SAPPHIRE_VT_MAX_POLL_ATTEMPTS}" \
  --update-env-vars "SAPPHIRE_VT_POLL_INTERVAL_SECONDS=${SAPPHIRE_VT_POLL_INTERVAL_SECONDS}" \
  --update-env-vars "SAPPHIRE_SCOUT_AGENT_ID=${SAPPHIRE_SCOUT_AGENT_ID}" \
  --update-env-vars "SAPPHIRE_SCOUT_DISPATCH_AGENT_ID=${SAPPHIRE_SCOUT_DISPATCH_AGENT_ID}" \
  --update-env-vars "SAPPHIRE_SCOUT_OPENCLAW_HOOK_URL=${SAPPHIRE_SCOUT_OPENCLAW_HOOK_URL}"

if [[ -n "${SAPPHIRE_SCOUT_OPENCLAW_CHAT_ID}" ]]; then
  gcloud run services update "${SERVICE_NAME}" \
    --project "${PROJECT_ID}" \
    --region "${REGION}" \
    --update-env-vars "SAPPHIRE_SCOUT_OPENCLAW_CHAT_ID=${SAPPHIRE_SCOUT_OPENCLAW_CHAT_ID}" >/dev/null
  echo "Applied explicit SAPPHIRE_SCOUT_OPENCLAW_CHAT_ID override."
fi

SCOUT_SECRET_MAPPINGS=()
if has_secret "${SCOUT_REGISTER_URL_SECRET}"; then
  SCOUT_SECRET_MAPPINGS+=("SAPPHIRE_SCOUT_EXTERNAL_REGISTER_URL=${SCOUT_REGISTER_URL_SECRET}:latest")
fi
if has_secret "${SCOUT_POST_URL_SECRET}"; then
  SCOUT_SECRET_MAPPINGS+=("SAPPHIRE_SCOUT_EXTERNAL_POST_URL=${SCOUT_POST_URL_SECRET}:latest")
fi
if has_secret "${SCOUT_API_TOKEN_SECRET}"; then
  SCOUT_SECRET_MAPPINGS+=("SAPPHIRE_SCOUT_EXTERNAL_API_TOKEN=${SCOUT_API_TOKEN_SECRET}:latest")
fi

if [[ "${#SCOUT_SECRET_MAPPINGS[@]}" -gt 0 ]]; then
  SCOUT_SECRET_ARG="$(IFS=,; echo "${SCOUT_SECRET_MAPPINGS[*]}")"
  echo "Applying scout external bridge secrets to ${SERVICE_NAME}: ${SCOUT_SECRET_ARG}"
  gcloud run services update "${SERVICE_NAME}" \
    --project "${PROJECT_ID}" \
    --region "${REGION}" \
    --update-secrets "${SCOUT_SECRET_ARG}" >/dev/null
  echo "Scout external bridge secret bindings applied."
else
  echo "Scout external bridge secrets not found yet; keeping OpenClaw fallback active."
fi

if has_secret "${VIRUSTOTAL_API_KEY_SECRET}"; then
  echo "Applying VirusTotal API secret binding to ${SERVICE_NAME}."
  gcloud run services update "${SERVICE_NAME}" \
    --project "${PROJECT_ID}" \
    --region "${REGION}" \
    --update-secrets "VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY_SECRET}:latest" >/dev/null
  echo "VirusTotal secret binding applied."
else
  echo "VirusTotal secret ${VIRUSTOTAL_API_KEY_SECRET} not found; VT scans will remain unavailable."
fi

SERVICE_URL="$(gcloud run services describe "${SERVICE_NAME}" --project "${PROJECT_ID}" --region "${REGION}" --format='value(status.url)')"
echo
echo "Service URL: ${SERVICE_URL}"
echo "Health:"
curl -fsS "${SERVICE_URL}/health" || true
echo
echo "Deployed image: ${IMAGE_URI}"
