#!/usr/bin/env bash
# Build and deploy sapphire-alpha control plane.

set -euo pipefail

PROJECT_ID="${PROJECT_ID:-sapphire-479610}"
REGION="${REGION:-us-central1}"
AR_REGION="${AR_REGION:-northamerica-northeast1}"
AR_REPO="${AR_REPO:-sapphire-repo}"
SERVICE_NAME="${SERVICE_NAME:-sapphire-alpha}"
IMAGE_NAME="${IMAGE_NAME:-sapphire-alpha}"
IMAGE_TAG="${IMAGE_TAG:-$(date -u +%Y%m%d%H%M)-alpha}"
PLATFORM="${PLATFORM:-linux/amd64}"
CPU="${CPU:-1}"
MEMORY="${MEMORY:-1Gi}"
CONCURRENCY="${CONCURRENCY:-80}"
TIMEOUT="${TIMEOUT:-300}"
MIN_INSTANCES="${MIN_INSTANCES:-1}"
PORT="${PORT:-8080}"
SERVICE_ACCOUNT="${SERVICE_ACCOUNT:-sapphire-main-sa@${PROJECT_ID}.iam.gserviceaccount.com}"
BUILD_SERVICE_ACCOUNT="${BUILD_SERVICE_ACCOUNT:-sapphirev3@${PROJECT_ID}.iam.gserviceaccount.com}"
FULL_AUTONOMY_ENABLED="${FULL_AUTONOMY_ENABLED:-true}"
AUTONOMY_ALLOW_CODE_CHANGES="${AUTONOMY_ALLOW_CODE_CHANGES:-true}"
AUTONOMY_ALLOW_GCLOUD_CHANGES="${AUTONOMY_ALLOW_GCLOUD_CHANGES:-true}"
AUTONOMY_DRY_RUN="${AUTONOMY_DRY_RUN:-false}"
AUTONOMY_REQUIRE_OWNER_APPROVAL="${AUTONOMY_REQUIRE_OWNER_APPROVAL:-false}"
AUTONOMY_LOOP_SECONDS="${AUTONOMY_LOOP_SECONDS:-900}"
AUTONOMY_MIN_DISPATCH_INTERVAL_SECONDS="${AUTONOMY_MIN_DISPATCH_INTERVAL_SECONDS:-600}"
GEMINI_FLASH_MIN_INTERVAL_SECONDS="${GEMINI_FLASH_MIN_INTERVAL_SECONDS:-1800}"
GEMINI_FLASH_MODEL="${GEMINI_FLASH_MODEL:-gemini-3-flash-preview}"
GEMINI_PRO_MODEL="${GEMINI_PRO_MODEL:-gemini-3-pro-preview}"
# TradingView integration disabled — using DEX-native data only
SAPPHIRE_TRADINGVIEW_INTEGRATION_ENABLED="${SAPPHIRE_TRADINGVIEW_INTEGRATION_ENABLED:-false}"
TRADINGVIEW_EXECUTION_ENABLED="${TRADINGVIEW_EXECUTION_ENABLED:-false}"
TRADINGVIEW_DEFAULT_QUANTITY="${TRADINGVIEW_DEFAULT_QUANTITY:-0.0}"
TRADINGVIEW_ENFORCE_STRATEGY_RULES="${TRADINGVIEW_ENFORCE_STRATEGY_RULES:-false}"
TRADINGVIEW_AUTONOMY_ENABLED="${TRADINGVIEW_AUTONOMY_ENABLED:-true}"
TRADINGVIEW_AUTONOMY_ALLOW_MUTATIONS="${TRADINGVIEW_AUTONOMY_ALLOW_MUTATIONS:-true}"
TRADINGVIEW_ALLOW_ALL_ASSETS="${TRADINGVIEW_ALLOW_ALL_ASSETS:-true}"
TRADINGVIEW_COMMUNITY_ACCESS_ENABLED="${TRADINGVIEW_COMMUNITY_ACCESS_ENABLED:-true}"
TRADINGVIEW_AUTONOMY_HOOK_URL="${TRADINGVIEW_AUTONOMY_HOOK_URL:-https://sapphire-gateway-s77j6bxyra-uc.a.run.app/hooks/agent}"
TRADINGVIEW_AUTONOMY_AGENT_ID="${TRADINGVIEW_AUTONOMY_AGENT_ID:-sapphire}"
TRADINGVIEW_IDEMPOTENCY_WINDOW_SECONDS="${TRADINGVIEW_IDEMPOTENCY_WINDOW_SECONDS:-300}"
TRADINGVIEW_IDEMPOTENCY_MAX_KEYS="${TRADINGVIEW_IDEMPOTENCY_MAX_KEYS:-2000}"
TRADINGVIEW_MAX_QUANTITY_ASTER="${TRADINGVIEW_MAX_QUANTITY_ASTER:-0.25}"
TRADINGVIEW_MAX_QUANTITY_LIGHTER="${TRADINGVIEW_MAX_QUANTITY_LIGHTER:-0.25}"
TRADINGVIEW_ALLOWED_SYMBOLS_ASTER="${TRADINGVIEW_ALLOWED_SYMBOLS_ASTER:-SOL;JUP;PYTH;BONK;WIF}"
TRADINGVIEW_ALLOWED_SYMBOLS_LIGHTER="${TRADINGVIEW_ALLOWED_SYMBOLS_LIGHTER:-BTC;ETH;SOL;HYPE;DOGE;AVAX}"
ENABLED_VENUES="${ENABLED_VENUES:-ASTER;LIGHTER}"
BOT_ASTER_URL="${BOT_ASTER_URL:-https://sapphire-aster-267358751314.us-central1.run.app}"
BOT_LIGHTER_URL="${BOT_LIGHTER_URL:-https://sapphire-lighter-267358751314.europe-west1.run.app}"
TELEGRAM_HEARTBEAT_INTERVAL_SECONDS="${TELEGRAM_HEARTBEAT_INTERVAL_SECONDS:-900}"
TELEGRAM_WEBHOOK_URL="${TELEGRAM_WEBHOOK_URL:-https://sapphire-alpha-267358751314.us-central1.run.app/telegram/webhook}"
INTERNAL_ARB_EXECUTION_ENABLED="${INTERNAL_ARB_EXECUTION_ENABLED:-true}"
INTERNAL_ARB_EXECUTION_QUANTITY="${INTERNAL_ARB_EXECUTION_QUANTITY:-0.02}"
SAPPHIRE_DEX_EXECUTION_STAGE="${SAPPHIRE_DEX_EXECUTION_STAGE:-full_live}"
SAPPHIRE_MIN_NOTIONAL_ASTER="${SAPPHIRE_MIN_NOTIONAL_ASTER:-5.0}"
SAPPHIRE_MIN_NOTIONAL_LIGHTER="${SAPPHIRE_MIN_NOTIONAL_LIGHTER:-10.0}"
SAPPHIRE_MIN_NOTIONAL_BUFFER_PCT="${SAPPHIRE_MIN_NOTIONAL_BUFFER_PCT:-0.05}"
SAPPHIRE_MIN_TRADE_QUANTITY_FLOOR="${SAPPHIRE_MIN_TRADE_QUANTITY_FLOOR:-0.0001}"
SAPPHIRE_TV_TAKE_PROFIT_PCT="${SAPPHIRE_TV_TAKE_PROFIT_PCT:-3.0}"
SAPPHIRE_TV_STOP_LOSS_PCT="${SAPPHIRE_TV_STOP_LOSS_PCT:-2.0}"
SAPPHIRE_TV_TRAILING_STOP="${SAPPHIRE_TV_TRAILING_STOP:-true}"
SAPPHIRE_TV_TRAILING_STOP_PCT="${SAPPHIRE_TV_TRAILING_STOP_PCT:-1.5}"
ALPHA_API_CORS_ORIGINS="${ALPHA_API_CORS_ORIGINS:-https://sapphirealpha.xyz;https://sapphirebook-web-s77j6bxyra-uc.a.run.app;https://sapphire-479610.web.app;http://localhost:5173;http://127.0.0.1:5173}"
GCP_PROJECT_ID_ENV="${GCP_PROJECT_ID_ENV:-${PROJECT_ID}}"
SERVICE_NAME_ENV="${SERVICE_NAME_ENV:-alpha-engine}"
PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
SAPPHIRE_ALLOWED_REPOS="${SAPPHIRE_ALLOWED_REPOS:-arigatoexpress/Sapphire;Sapphire}"
SAPPHIRE_ALLOWED_GCP_PROJECTS="${SAPPHIRE_ALLOWED_GCP_PROJECTS:-${PROJECT_ID}}"
SAPPHIRE_BLOCKED_SCOPE_TERMS="${SAPPHIRE_BLOCKED_SCOPE_TERMS:-sapphireai;sapphire-inc;sapphire_inc;tho-agent;tho_agent}"
SAPPHIRE_SCOUT_AGENT_ID="${SAPPHIRE_SCOUT_AGENT_ID:-SAPPHIRE_SCOUT}"
SAPPHIRE_SCOUT_DISPATCH_AGENT_ID="${SAPPHIRE_SCOUT_DISPATCH_AGENT_ID:-scout}"
SAPPHIRE_SCOUT_OPENCLAW_CHAT_ID="${SAPPHIRE_SCOUT_OPENCLAW_CHAT_ID:-${TELEGRAM_CHAT_ID:-}}"
SAPPHIRE_SCOUT_OPENCLAW_HOOK_URL="${SAPPHIRE_SCOUT_OPENCLAW_HOOK_URL:-https://sapphire-openclaw-cloud-267358751314.us-central1.run.app/hooks/agent}"
OPENCLAW_GATEWAY_URL="${OPENCLAW_GATEWAY_URL:-https://sapphire-openclaw-cloud-267358751314.us-central1.run.app}"
SAPPHIRE_SCOUT_SANDBOX_URL="${SAPPHIRE_SCOUT_SANDBOX_URL:-https://sapphire-scout-sandbox-267358751314.us-central1.run.app}"
SAPPHIRE_SCOUT_SANDBOX_ENFORCE="${SAPPHIRE_SCOUT_SANDBOX_ENFORCE:-true}"
SAPPHIRE_INTEL_FEED_ENABLED="${SAPPHIRE_INTEL_FEED_ENABLED:-true}"
SAPPHIRE_GLINT_SCRAPE_ENABLED="${SAPPHIRE_GLINT_SCRAPE_ENABLED:-true}"
SAPPHIRE_GLINT_USE_SCOUT_SANDBOX="${SAPPHIRE_GLINT_USE_SCOUT_SANDBOX:-true}"
SAPPHIRE_GLINT_SCRAPE_SANDBOX_ONLY="${SAPPHIRE_GLINT_SCRAPE_SANDBOX_ONLY:-true}"
SAPPHIRE_GLINT_SOURCE_URL="${SAPPHIRE_GLINT_SOURCE_URL:-https://glint.trade/feed}"
SAPPHIRE_GLINT_SANDBOX_LIMIT="${SAPPHIRE_GLINT_SANDBOX_LIMIT:-24}"
SAPPHIRE_GLINT_SANDBOX_QUERY="${SAPPHIRE_GLINT_SANDBOX_QUERY:-}"
SAPPHIRE_GLINT_SANDBOX_TIMEOUT_SECONDS="${SAPPHIRE_GLINT_SANDBOX_TIMEOUT_SECONDS:-14}"
SAPPHIRE_SCRAPLING_INTEL_ENABLED="${SAPPHIRE_SCRAPLING_INTEL_ENABLED:-true}"
SAPPHIRE_SCRAPLING_INTEL_SOURCE_URL="${SAPPHIRE_SCRAPLING_INTEL_SOURCE_URL:-https://news.ycombinator.com/}"
SAPPHIRE_SCRAPLING_INTEL_SELECTORS="${SAPPHIRE_SCRAPLING_INTEL_SELECTORS:-title;h1;h2;a}"
SAPPHIRE_SCRAPLING_INTEL_LIMIT_PER_SELECTOR="${SAPPHIRE_SCRAPLING_INTEL_LIMIT_PER_SELECTOR:-4}"
SAPPHIRE_SCRAPLING_INTEL_INCLUDE_LINKS="${SAPPHIRE_SCRAPLING_INTEL_INCLUDE_LINKS:-true}"
SAPPHIRE_SCRAPLING_INTEL_MAX_LINKS="${SAPPHIRE_SCRAPLING_INTEL_MAX_LINKS:-20}"
SAPPHIRE_SCRAPLING_INTEL_QUERY="${SAPPHIRE_SCRAPLING_INTEL_QUERY:-}"
SAPPHIRE_SCRAPLING_INTEL_TIMEOUT_SECONDS="${SAPPHIRE_SCRAPLING_INTEL_TIMEOUT_SECONDS:-20}"
SAPPHIRE_SCOUT_GTM_OUTBOUND_URL="${SAPPHIRE_SCOUT_GTM_OUTBOUND_URL:-}"
SCOUT_REGISTER_URL_SECRET="${SCOUT_REGISTER_URL_SECRET:-SAPPHIRE_SCOUT_EXTERNAL_REGISTER_URL}"
SCOUT_POST_URL_SECRET="${SCOUT_POST_URL_SECRET:-SAPPHIRE_SCOUT_EXTERNAL_POST_URL}"
SCOUT_API_TOKEN_SECRET="${SCOUT_API_TOKEN_SECRET:-SAPPHIRE_SCOUT_EXTERNAL_API_TOKEN}"
SCOUT_GTM_API_TOKEN_SECRET="${SCOUT_GTM_API_TOKEN_SECRET:-SCOUT_SANDBOX_GTM_API_TOKEN}"
SCOUT_SANDBOX_TOKEN_SECRET="${SCOUT_SANDBOX_TOKEN_SECRET:-SAPPHIRE_SCOUT_SANDBOX_TOKEN}"
SCOUT_OPENCLAW_HOOK_TOKEN_SECRET="${SCOUT_OPENCLAW_HOOK_TOKEN_SECRET:-OPENCLAW_GATEWAY_TOKEN}"
CONTROL_API_TOKEN_SECRET="${CONTROL_API_TOKEN_SECRET:-SAPPHIRE_CONTROL_API_TOKEN}"
SAPPHIRE_VT_ENABLED="${SAPPHIRE_VT_ENABLED:-true}"
SAPPHIRE_VT_ENFORCEMENT_MODE="${SAPPHIRE_VT_ENFORCEMENT_MODE:-block_malicious}"
SAPPHIRE_VT_UPLOAD_IF_MISSING="${SAPPHIRE_VT_UPLOAD_IF_MISSING:-false}"
SAPPHIRE_VT_MAX_POLL_ATTEMPTS="${SAPPHIRE_VT_MAX_POLL_ATTEMPTS:-4}"
SAPPHIRE_VT_POLL_INTERVAL_SECONDS="${SAPPHIRE_VT_POLL_INTERVAL_SECONDS:-30}"
SAPPHIRE_VT_MAX_SKILLS_PER_SCAN="${SAPPHIRE_VT_MAX_SKILLS_PER_SCAN:-4}"
SAPPHIRE_VT_MAX_REQUESTS_PER_MINUTE="${SAPPHIRE_VT_MAX_REQUESTS_PER_MINUTE:-4}"
SAPPHIRE_VT_MAX_REQUESTS_PER_DAY="${SAPPHIRE_VT_MAX_REQUESTS_PER_DAY:-500}"
VIRUSTOTAL_API_KEY_SECRET="${VIRUSTOTAL_API_KEY_SECRET:-VIRUSTOTAL_API_KEY}"
SAPPHIRE_MEDIA_MODE="${SAPPHIRE_MEDIA_MODE:-owner_approval}"
SAPPHIRE_MEDIA_TWITTER_ENABLED="${SAPPHIRE_MEDIA_TWITTER_ENABLED:-true}"
SAPPHIRE_MEDIA_SUBSTACK_ENABLED="${SAPPHIRE_MEDIA_SUBSTACK_ENABLED:-true}"
SAPPHIRE_TWITTER_HANDLE="${SAPPHIRE_TWITTER_HANDLE:-}"
SAPPHIRE_SUBSTACK_PUBLICATION_URL="${SAPPHIRE_SUBSTACK_PUBLICATION_URL:-}"
SAPPHIRE_SUBSTACK_PUBLICATION_EMAIL="${SAPPHIRE_SUBSTACK_PUBLICATION_EMAIL:-}"
SAPPHIRE_SUBSTACK_FROM_EMAIL="${SAPPHIRE_SUBSTACK_FROM_EMAIL:-}"
SAPPHIRE_SUBSTACK_FROM_NAME="${SAPPHIRE_SUBSTACK_FROM_NAME:-Sapphire Inc. 🤖}"
SAPPHIRE_SUBSTACK_SMTP_HOST="${SAPPHIRE_SUBSTACK_SMTP_HOST:-}"
SAPPHIRE_SUBSTACK_SMTP_PORT="${SAPPHIRE_SUBSTACK_SMTP_PORT:-587}"
SAPPHIRE_SUBSTACK_SMTP_USERNAME="${SAPPHIRE_SUBSTACK_SMTP_USERNAME:-}"
SAPPHIRE_SUBSTACK_SMTP_USE_TLS="${SAPPHIRE_SUBSTACK_SMTP_USE_TLS:-true}"
SAPPHIRE_MEDIA_TWITTER_POST_URL="${SAPPHIRE_MEDIA_TWITTER_POST_URL:-}"
SAPPHIRE_MEDIA_SUBSTACK_POST_URL="${SAPPHIRE_MEDIA_SUBSTACK_POST_URL:-}"
SAPPHIRE_MEDIA_MAX_ATTEMPTS="${SAPPHIRE_MEDIA_MAX_ATTEMPTS:-4}"
SAPPHIRE_MEDIA_RETRY_BASE_SECONDS="${SAPPHIRE_MEDIA_RETRY_BASE_SECONDS:-120}"
SAPPHIRE_MEDIA_POST_TIMEOUT_SECONDS="${SAPPHIRE_MEDIA_POST_TIMEOUT_SECONDS:-20}"
SAPPHIRE_MEDIA_POLL_SECONDS="${SAPPHIRE_MEDIA_POLL_SECONDS:-20}"
SAPPHIRE_MEDIA_QUEUE_MAX_ITEMS="${SAPPHIRE_MEDIA_QUEUE_MAX_ITEMS:-200}"
TWITTER_API_TOKEN_SECRET="${TWITTER_API_TOKEN_SECRET:-SAPPHIRE_TWITTER_API_TOKEN}"
SUBSTACK_API_TOKEN_SECRET="${SUBSTACK_API_TOKEN_SECRET:-SAPPHIRE_SUBSTACK_API_TOKEN}"
SUBSTACK_SMTP_PASSWORD_SECRET="${SUBSTACK_SMTP_PASSWORD_SECRET:-SAPPHIRE_SUBSTACK_SMTP_PASSWORD}"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ALPHA_DIR="${ROOT_DIR}/services/alpha-engine"
if [[ -x "${ROOT_DIR}/scripts/check_source_of_truth.sh" ]]; then
  "${ROOT_DIR}/scripts/check_source_of_truth.sh"
fi
IMAGE_URI="${AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPO}/${IMAGE_NAME}:${IMAGE_TAG}"
IMAGE_LATEST="${AR_REGION}-docker.pkg.dev/${PROJECT_ID}/${AR_REPO}/${IMAGE_NAME}:latest"

has_secret() {
  local name="$1"
  gcloud secrets describe "${name}" --project "${PROJECT_ID}" >/dev/null 2>&1
}

echo "== Sapphire Alpha Deploy =="
echo "Project: ${PROJECT_ID}"
echo "Region: ${REGION}"
echo "Image: ${IMAGE_URI}"
echo

if [[ "${SKIP_BUILD:-false}" != "true" ]]; then
  if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
    docker buildx build \
      --platform "${PLATFORM}" \
      -f "${ALPHA_DIR}/Dockerfile" \
      -t "${IMAGE_URI}" \
      -t "${IMAGE_LATEST}" \
      --push "${ROOT_DIR}"
  else
    echo "Docker daemon unavailable; using Cloud Build fallback."
    gcloud builds submit \
      --project "${PROJECT_ID}" \
      --service-account "projects/${PROJECT_ID}/serviceAccounts/${BUILD_SERVICE_ACCOUNT}" \
      --default-buckets-behavior=regional-user-owned-bucket \
      --config "${ROOT_DIR}/cloudbuild-alpha.yaml" \
      --substitutions "_IMAGE=${IMAGE_URI}" \
      "${ROOT_DIR}"
    gcloud artifacts docker tags add "${IMAGE_URI}" "${IMAGE_LATEST}" --project "${PROJECT_ID}" >/dev/null
  fi
fi

gcloud run deploy "${SERVICE_NAME}" \
  --project "${PROJECT_ID}" \
  --region "${REGION}" \
  --image "${IMAGE_URI}" \
  --platform managed \
  --allow-unauthenticated \
  --service-account "${SERVICE_ACCOUNT}" \
  --memory "${MEMORY}" \
  --cpu "${CPU}" \
  --concurrency "${CONCURRENCY}" \
  --timeout "${TIMEOUT}" \
  --min-instances "${MIN_INSTANCES}" \
  --port "${PORT}" \
  --update-env-vars "GCP_PROJECT_ID=${GCP_PROJECT_ID_ENV}" \
  --update-env-vars "SERVICE_NAME=${SERVICE_NAME_ENV}" \
  --update-env-vars "PYTHONUNBUFFERED=${PYTHONUNBUFFERED}" \
  --update-env-vars "ENABLED_VENUES=${ENABLED_VENUES}" \
  --update-env-vars "BOT_ASTER_URL=${BOT_ASTER_URL}" \
  --update-env-vars "BOT_LIGHTER_URL=${BOT_LIGHTER_URL}" \
  --update-env-vars "TELEGRAM_HEARTBEAT_INTERVAL_SECONDS=${TELEGRAM_HEARTBEAT_INTERVAL_SECONDS}" \
  --update-env-vars "TELEGRAM_WEBHOOK_URL=${TELEGRAM_WEBHOOK_URL}" \
  --update-env-vars "TRADINGVIEW_IDEMPOTENCY_WINDOW_SECONDS=${TRADINGVIEW_IDEMPOTENCY_WINDOW_SECONDS}" \
  --update-env-vars "TRADINGVIEW_IDEMPOTENCY_MAX_KEYS=${TRADINGVIEW_IDEMPOTENCY_MAX_KEYS}" \
  --update-env-vars "TRADINGVIEW_MAX_QUANTITY_ASTER=${TRADINGVIEW_MAX_QUANTITY_ASTER}" \
  --update-env-vars "TRADINGVIEW_MAX_QUANTITY_LIGHTER=${TRADINGVIEW_MAX_QUANTITY_LIGHTER}" \
  --update-env-vars "TRADINGVIEW_ALLOWED_SYMBOLS_ASTER=${TRADINGVIEW_ALLOWED_SYMBOLS_ASTER}" \
  --update-env-vars "TRADINGVIEW_ALLOWED_SYMBOLS_LIGHTER=${TRADINGVIEW_ALLOWED_SYMBOLS_LIGHTER}" \
  --update-env-vars "TRADINGVIEW_ENFORCE_STRATEGY_RULES=${TRADINGVIEW_ENFORCE_STRATEGY_RULES}" \
  --update-env-vars "TRADINGVIEW_AUTONOMY_ENABLED=${TRADINGVIEW_AUTONOMY_ENABLED}" \
  --update-env-vars "TRADINGVIEW_AUTONOMY_ALLOW_MUTATIONS=${TRADINGVIEW_AUTONOMY_ALLOW_MUTATIONS}" \
  --update-env-vars "TRADINGVIEW_ALLOW_ALL_ASSETS=${TRADINGVIEW_ALLOW_ALL_ASSETS}" \
  --update-env-vars "TRADINGVIEW_COMMUNITY_ACCESS_ENABLED=${TRADINGVIEW_COMMUNITY_ACCESS_ENABLED}" \
  --update-env-vars "TRADINGVIEW_AUTONOMY_HOOK_URL=${TRADINGVIEW_AUTONOMY_HOOK_URL}" \
  --update-env-vars "TRADINGVIEW_AUTONOMY_AGENT_ID=${TRADINGVIEW_AUTONOMY_AGENT_ID}" \
  --update-env-vars "ALPHA_API_CORS_ORIGINS=${ALPHA_API_CORS_ORIGINS}" \
  --update-env-vars "INTERNAL_ARB_EXECUTION_ENABLED=${INTERNAL_ARB_EXECUTION_ENABLED}" \
  --update-env-vars "INTERNAL_ARB_EXECUTION_QUANTITY=${INTERNAL_ARB_EXECUTION_QUANTITY}" \
  --update-env-vars "SAPPHIRE_DEX_EXECUTION_STAGE=${SAPPHIRE_DEX_EXECUTION_STAGE}" \
  --update-env-vars "SAPPHIRE_MIN_NOTIONAL_ASTER=${SAPPHIRE_MIN_NOTIONAL_ASTER}" \
  --update-env-vars "SAPPHIRE_MIN_NOTIONAL_LIGHTER=${SAPPHIRE_MIN_NOTIONAL_LIGHTER}" \
  --update-env-vars "SAPPHIRE_MIN_NOTIONAL_BUFFER_PCT=${SAPPHIRE_MIN_NOTIONAL_BUFFER_PCT}" \
  --update-env-vars "SAPPHIRE_MIN_TRADE_QUANTITY_FLOOR=${SAPPHIRE_MIN_TRADE_QUANTITY_FLOOR}" \
  --update-env-vars "SAPPHIRE_TV_TAKE_PROFIT_PCT=${SAPPHIRE_TV_TAKE_PROFIT_PCT}" \
  --update-env-vars "SAPPHIRE_TV_STOP_LOSS_PCT=${SAPPHIRE_TV_STOP_LOSS_PCT}" \
  --update-env-vars "SAPPHIRE_TV_TRAILING_STOP=${SAPPHIRE_TV_TRAILING_STOP}" \
  --update-env-vars "SAPPHIRE_TV_TRAILING_STOP_PCT=${SAPPHIRE_TV_TRAILING_STOP_PCT}" \
  --update-env-vars "SAPPHIRE_FULL_AUTONOMY_ENABLED=${FULL_AUTONOMY_ENABLED}" \
  --update-env-vars "SAPPHIRE_AUTONOMY_ALLOW_CODE_CHANGES=${AUTONOMY_ALLOW_CODE_CHANGES}" \
  --update-env-vars "SAPPHIRE_AUTONOMY_ALLOW_GCLOUD_CHANGES=${AUTONOMY_ALLOW_GCLOUD_CHANGES}" \
  --update-env-vars "SAPPHIRE_AUTONOMY_DRY_RUN=${AUTONOMY_DRY_RUN}" \
  --update-env-vars "SAPPHIRE_AUTONOMY_REQUIRE_OWNER_APPROVAL=${AUTONOMY_REQUIRE_OWNER_APPROVAL}" \
  --update-env-vars "SAPPHIRE_AUTONOMY_LOOP_SECONDS=${AUTONOMY_LOOP_SECONDS}" \
  --update-env-vars "SAPPHIRE_AUTONOMY_MIN_DISPATCH_INTERVAL_SECONDS=${AUTONOMY_MIN_DISPATCH_INTERVAL_SECONDS}" \
  --update-env-vars "GEMINI_FLASH_MIN_INTERVAL_SECONDS=${GEMINI_FLASH_MIN_INTERVAL_SECONDS}" \
  --update-env-vars "GEMINI_FLASH_MODEL=${GEMINI_FLASH_MODEL}" \
  --update-env-vars "GEMINI_PRO_MODEL=${GEMINI_PRO_MODEL}" \
  --update-env-vars "SAPPHIRE_TRADINGVIEW_INTEGRATION_ENABLED=${SAPPHIRE_TRADINGVIEW_INTEGRATION_ENABLED}" \
  --update-env-vars "TRADINGVIEW_EXECUTION_ENABLED=${TRADINGVIEW_EXECUTION_ENABLED}" \
  --update-env-vars "TRADINGVIEW_DEFAULT_QUANTITY=${TRADINGVIEW_DEFAULT_QUANTITY}" \
  --update-env-vars "SAPPHIRE_ALLOWED_REPOS=${SAPPHIRE_ALLOWED_REPOS}" \
  --update-env-vars "SAPPHIRE_ALLOWED_GCP_PROJECTS=${SAPPHIRE_ALLOWED_GCP_PROJECTS}" \
  --update-env-vars "SAPPHIRE_BLOCKED_SCOPE_TERMS=${SAPPHIRE_BLOCKED_SCOPE_TERMS}" \
  --update-env-vars "SAPPHIRE_VT_ENABLED=${SAPPHIRE_VT_ENABLED}" \
  --update-env-vars "SAPPHIRE_VT_ENFORCEMENT_MODE=${SAPPHIRE_VT_ENFORCEMENT_MODE}" \
  --update-env-vars "SAPPHIRE_VT_UPLOAD_IF_MISSING=${SAPPHIRE_VT_UPLOAD_IF_MISSING}" \
  --update-env-vars "SAPPHIRE_VT_MAX_POLL_ATTEMPTS=${SAPPHIRE_VT_MAX_POLL_ATTEMPTS}" \
  --update-env-vars "SAPPHIRE_VT_POLL_INTERVAL_SECONDS=${SAPPHIRE_VT_POLL_INTERVAL_SECONDS}" \
  --update-env-vars "SAPPHIRE_VT_MAX_SKILLS_PER_SCAN=${SAPPHIRE_VT_MAX_SKILLS_PER_SCAN}" \
  --update-env-vars "SAPPHIRE_VT_MAX_REQUESTS_PER_MINUTE=${SAPPHIRE_VT_MAX_REQUESTS_PER_MINUTE}" \
  --update-env-vars "SAPPHIRE_VT_MAX_REQUESTS_PER_DAY=${SAPPHIRE_VT_MAX_REQUESTS_PER_DAY}" \
  --update-env-vars "SAPPHIRE_MEDIA_MODE=${SAPPHIRE_MEDIA_MODE}" \
  --update-env-vars "SAPPHIRE_MEDIA_TWITTER_ENABLED=${SAPPHIRE_MEDIA_TWITTER_ENABLED}" \
  --update-env-vars "SAPPHIRE_MEDIA_SUBSTACK_ENABLED=${SAPPHIRE_MEDIA_SUBSTACK_ENABLED}" \
  --update-env-vars "SAPPHIRE_TWITTER_HANDLE=${SAPPHIRE_TWITTER_HANDLE}" \
  --update-env-vars "SAPPHIRE_SUBSTACK_PUBLICATION_URL=${SAPPHIRE_SUBSTACK_PUBLICATION_URL}" \
  --update-env-vars "SAPPHIRE_SUBSTACK_PUBLICATION_EMAIL=${SAPPHIRE_SUBSTACK_PUBLICATION_EMAIL}" \
  --update-env-vars "SAPPHIRE_SUBSTACK_FROM_EMAIL=${SAPPHIRE_SUBSTACK_FROM_EMAIL}" \
  --update-env-vars "SAPPHIRE_SUBSTACK_FROM_NAME=${SAPPHIRE_SUBSTACK_FROM_NAME}" \
  --update-env-vars "SAPPHIRE_SUBSTACK_SMTP_HOST=${SAPPHIRE_SUBSTACK_SMTP_HOST}" \
  --update-env-vars "SAPPHIRE_SUBSTACK_SMTP_PORT=${SAPPHIRE_SUBSTACK_SMTP_PORT}" \
  --update-env-vars "SAPPHIRE_SUBSTACK_SMTP_USERNAME=${SAPPHIRE_SUBSTACK_SMTP_USERNAME}" \
  --update-env-vars "SAPPHIRE_SUBSTACK_SMTP_USE_TLS=${SAPPHIRE_SUBSTACK_SMTP_USE_TLS}" \
  --update-env-vars "SAPPHIRE_MEDIA_TWITTER_POST_URL=${SAPPHIRE_MEDIA_TWITTER_POST_URL}" \
  --update-env-vars "SAPPHIRE_MEDIA_SUBSTACK_POST_URL=${SAPPHIRE_MEDIA_SUBSTACK_POST_URL}" \
  --update-env-vars "SAPPHIRE_MEDIA_MAX_ATTEMPTS=${SAPPHIRE_MEDIA_MAX_ATTEMPTS}" \
  --update-env-vars "SAPPHIRE_MEDIA_RETRY_BASE_SECONDS=${SAPPHIRE_MEDIA_RETRY_BASE_SECONDS}" \
  --update-env-vars "SAPPHIRE_MEDIA_POST_TIMEOUT_SECONDS=${SAPPHIRE_MEDIA_POST_TIMEOUT_SECONDS}" \
  --update-env-vars "SAPPHIRE_MEDIA_POLL_SECONDS=${SAPPHIRE_MEDIA_POLL_SECONDS}" \
  --update-env-vars "SAPPHIRE_MEDIA_QUEUE_MAX_ITEMS=${SAPPHIRE_MEDIA_QUEUE_MAX_ITEMS}" \
  --update-env-vars "SAPPHIRE_SCOUT_AGENT_ID=${SAPPHIRE_SCOUT_AGENT_ID}" \
  --update-env-vars "SAPPHIRE_SCOUT_DISPATCH_AGENT_ID=${SAPPHIRE_SCOUT_DISPATCH_AGENT_ID}" \
  --update-env-vars "OPENCLAW_GATEWAY_URL=${OPENCLAW_GATEWAY_URL}" \
  --update-env-vars "SAPPHIRE_SCOUT_SANDBOX_URL=${SAPPHIRE_SCOUT_SANDBOX_URL}" \
  --update-env-vars "SAPPHIRE_SCOUT_SANDBOX_ENFORCE=${SAPPHIRE_SCOUT_SANDBOX_ENFORCE}" \
  --update-env-vars "SAPPHIRE_INTEL_FEED_ENABLED=${SAPPHIRE_INTEL_FEED_ENABLED}" \
  --update-env-vars "SAPPHIRE_GLINT_SCRAPE_ENABLED=${SAPPHIRE_GLINT_SCRAPE_ENABLED}" \
  --update-env-vars "SAPPHIRE_GLINT_USE_SCOUT_SANDBOX=${SAPPHIRE_GLINT_USE_SCOUT_SANDBOX}" \
  --update-env-vars "SAPPHIRE_GLINT_SCRAPE_SANDBOX_ONLY=${SAPPHIRE_GLINT_SCRAPE_SANDBOX_ONLY}" \
  --update-env-vars "SAPPHIRE_GLINT_SOURCE_URL=${SAPPHIRE_GLINT_SOURCE_URL}" \
  --update-env-vars "SAPPHIRE_GLINT_SANDBOX_LIMIT=${SAPPHIRE_GLINT_SANDBOX_LIMIT}" \
  --update-env-vars "SAPPHIRE_GLINT_SANDBOX_QUERY=${SAPPHIRE_GLINT_SANDBOX_QUERY}" \
  --update-env-vars "SAPPHIRE_GLINT_SANDBOX_TIMEOUT_SECONDS=${SAPPHIRE_GLINT_SANDBOX_TIMEOUT_SECONDS}" \
  --update-env-vars "SAPPHIRE_SCRAPLING_INTEL_ENABLED=${SAPPHIRE_SCRAPLING_INTEL_ENABLED}" \
  --update-env-vars "SAPPHIRE_SCRAPLING_INTEL_SOURCE_URL=${SAPPHIRE_SCRAPLING_INTEL_SOURCE_URL}" \
  --update-env-vars "SAPPHIRE_SCRAPLING_INTEL_SELECTORS=${SAPPHIRE_SCRAPLING_INTEL_SELECTORS}" \
  --update-env-vars "SAPPHIRE_SCRAPLING_INTEL_LIMIT_PER_SELECTOR=${SAPPHIRE_SCRAPLING_INTEL_LIMIT_PER_SELECTOR}" \
  --update-env-vars "SAPPHIRE_SCRAPLING_INTEL_INCLUDE_LINKS=${SAPPHIRE_SCRAPLING_INTEL_INCLUDE_LINKS}" \
  --update-env-vars "SAPPHIRE_SCRAPLING_INTEL_MAX_LINKS=${SAPPHIRE_SCRAPLING_INTEL_MAX_LINKS}" \
  --update-env-vars "SAPPHIRE_SCRAPLING_INTEL_QUERY=${SAPPHIRE_SCRAPLING_INTEL_QUERY}" \
  --update-env-vars "SAPPHIRE_SCRAPLING_INTEL_TIMEOUT_SECONDS=${SAPPHIRE_SCRAPLING_INTEL_TIMEOUT_SECONDS}" \
  --update-env-vars "SAPPHIRE_SCOUT_GTM_OUTBOUND_URL=${SAPPHIRE_SCOUT_GTM_OUTBOUND_URL}" \
  --update-env-vars "SAPPHIRE_SCOUT_OPENCLAW_HOOK_URL=${SAPPHIRE_SCOUT_OPENCLAW_HOOK_URL}"

if [[ -n "${SAPPHIRE_SCOUT_OPENCLAW_CHAT_ID}" ]]; then
  gcloud run services update "${SERVICE_NAME}" \
    --project "${PROJECT_ID}" \
    --region "${REGION}" \
    --update-env-vars "SAPPHIRE_SCOUT_OPENCLAW_CHAT_ID=${SAPPHIRE_SCOUT_OPENCLAW_CHAT_ID}" >/dev/null
  echo "Applied explicit SAPPHIRE_SCOUT_OPENCLAW_CHAT_ID override."
fi

SCOUT_SECRET_MAPPINGS=()
if has_secret "${SCOUT_REGISTER_URL_SECRET}"; then
  SCOUT_SECRET_MAPPINGS+=("SAPPHIRE_SCOUT_EXTERNAL_REGISTER_URL=${SCOUT_REGISTER_URL_SECRET}:latest")
fi
if has_secret "${SCOUT_POST_URL_SECRET}"; then
  SCOUT_SECRET_MAPPINGS+=("SAPPHIRE_SCOUT_EXTERNAL_POST_URL=${SCOUT_POST_URL_SECRET}:latest")
fi
if has_secret "${SCOUT_API_TOKEN_SECRET}"; then
  SCOUT_SECRET_MAPPINGS+=("SAPPHIRE_SCOUT_EXTERNAL_API_TOKEN=${SCOUT_API_TOKEN_SECRET}:latest")
fi
if has_secret "${SCOUT_GTM_API_TOKEN_SECRET}"; then
  SCOUT_SECRET_MAPPINGS+=("SAPPHIRE_SCOUT_GTM_API_TOKEN=${SCOUT_GTM_API_TOKEN_SECRET}:latest")
fi
if has_secret "${SCOUT_SANDBOX_TOKEN_SECRET}"; then
  SCOUT_SECRET_MAPPINGS+=("SAPPHIRE_SCOUT_SANDBOX_TOKEN=${SCOUT_SANDBOX_TOKEN_SECRET}:latest")
fi
if has_secret "${SCOUT_OPENCLAW_HOOK_TOKEN_SECRET}"; then
  SCOUT_SECRET_MAPPINGS+=("SAPPHIRE_SCOUT_OPENCLAW_HOOK_TOKEN=${SCOUT_OPENCLAW_HOOK_TOKEN_SECRET}:latest")
fi

if [[ "${#SCOUT_SECRET_MAPPINGS[@]}" -gt 0 ]]; then
  SCOUT_SECRET_ARG="$(IFS=,; echo "${SCOUT_SECRET_MAPPINGS[*]}")"
  echo "Applying scout external bridge secrets to ${SERVICE_NAME}: ${SCOUT_SECRET_ARG}"
  gcloud run services update "${SERVICE_NAME}" \
    --project "${PROJECT_ID}" \
    --region "${REGION}" \
    --update-secrets "${SCOUT_SECRET_ARG}" >/dev/null
  echo "Scout external bridge secret bindings applied."
else
  echo "Scout external bridge secrets not found yet; keeping OpenClaw fallback active."
fi

if has_secret "${CONTROL_API_TOKEN_SECRET}"; then
  echo "Applying control API token secret binding to ${SERVICE_NAME}."
  gcloud run services update "${SERVICE_NAME}" \
    --project "${PROJECT_ID}" \
    --region "${REGION}" \
    --update-secrets "SAPPHIRE_CONTROL_API_TOKEN=${CONTROL_API_TOKEN_SECRET}:latest" >/dev/null
  echo "Control API token binding applied."
else
  echo "Control API token secret ${CONTROL_API_TOKEN_SECRET} not found; mutable API routes will be locked (503)."
fi

if has_secret "${VIRUSTOTAL_API_KEY_SECRET}"; then
  echo "Applying VirusTotal API secret binding to ${SERVICE_NAME}."
  gcloud run services update "${SERVICE_NAME}" \
    --project "${PROJECT_ID}" \
    --region "${REGION}" \
    --update-secrets "VIRUSTOTAL_API_KEY=${VIRUSTOTAL_API_KEY_SECRET}:latest" >/dev/null
  echo "VirusTotal secret binding applied."
else
  echo "VirusTotal secret ${VIRUSTOTAL_API_KEY_SECRET} not found; VT scans will remain unavailable."
fi

if has_secret "${TWITTER_API_TOKEN_SECRET}"; then
  echo "Applying Twitter API secret binding to ${SERVICE_NAME}."
  gcloud run services update "${SERVICE_NAME}" \
    --project "${PROJECT_ID}" \
    --region "${REGION}" \
    --update-secrets "SAPPHIRE_TWITTER_API_TOKEN=${TWITTER_API_TOKEN_SECRET}:latest" >/dev/null
  echo "Twitter API secret binding applied."
else
  echo "Twitter secret ${TWITTER_API_TOKEN_SECRET} not found; X publish path remains not-ready."
fi

if has_secret "${SUBSTACK_API_TOKEN_SECRET}"; then
  echo "Applying Substack API secret binding to ${SERVICE_NAME}."
  gcloud run services update "${SERVICE_NAME}" \
    --project "${PROJECT_ID}" \
    --region "${REGION}" \
    --update-secrets "SAPPHIRE_SUBSTACK_API_TOKEN=${SUBSTACK_API_TOKEN_SECRET}:latest" >/dev/null
  echo "Substack API secret binding applied."
else
  echo "Substack secret ${SUBSTACK_API_TOKEN_SECRET} not found; Substack publish path remains not-ready."
fi

if has_secret "${SUBSTACK_SMTP_PASSWORD_SECRET}"; then
  echo "Applying Substack SMTP password secret binding to ${SERVICE_NAME}."
  gcloud run services update "${SERVICE_NAME}" \
    --project "${PROJECT_ID}" \
    --region "${REGION}" \
    --update-secrets "SAPPHIRE_SUBSTACK_SMTP_PASSWORD=${SUBSTACK_SMTP_PASSWORD_SECRET}:latest" >/dev/null
  echo "Substack SMTP password binding applied."
else
  echo "Substack SMTP password secret ${SUBSTACK_SMTP_PASSWORD_SECRET} not found; email publish mode may be unavailable."
fi

SERVICE_URL="$(gcloud run services describe "${SERVICE_NAME}" --project "${PROJECT_ID}" --region "${REGION}" --format='value(status.url)')"
echo
echo "Service URL: ${SERVICE_URL}"
echo "Health:"
curl -fsS "${SERVICE_URL}/health" || true
echo
echo "Deployed image: ${IMAGE_URI}"
