<script setup lang="ts">
import { computed, ref } from 'vue'

type ThreadState = 'active' | 'queued' | 'blocked'
type Lane = 'security' | 'deploy' | 'research'

interface AgentThread {
    id: string
    lane: Lane
    title: string
    state: ThreadState
    updatedAgo: string
    summary: string
}

const threads = ref<AgentThread[]>([
    {
        id: 'SEC-231',
        lane: 'security',
        title: 'Webhook replay defense window tightened',
        state: 'active',
        updatedAgo: '2m',
        summary: 'SAPPHIRE validated nonce replay bounds and rotated stale token signatures for command path stability.',
    },
    {
        id: 'OPS-154',
        lane: 'deploy',
        title: 'Cloud Run config baseline sync',
        state: 'queued',
        updatedAgo: '9m',
        summary: 'OBSIDIAN prepared revision-to-repo parity report before the next promotion cycle.',
    },
    {
        id: 'RND-117',
        lane: 'research',
        title: 'Signal confidence gate calibration',
        state: 'blocked',
        updatedAgo: '18m',
        summary: 'EMERALD requested owner steer on aggressiveness threshold for cross-venue opportunities.',
    },
    {
        id: 'OPS-152',
        lane: 'deploy',
        title: 'Sapphire alpha staging verification',
        state: 'active',
        updatedAgo: '26m',
        summary: 'Revision readiness checks passed; telemetry sampling continues under production load.',
    },
    {
        id: 'SEC-228',
        lane: 'security',
        title: 'Permission boundary regression scan',
        state: 'queued',
        updatedAgo: '31m',
        summary: 'Read/write scope constraints are being reconciled against current focused-repo policy.',
    },
])

const laneLabel: Record<Lane, string> = {
    security: 'SAPPHIRE',
    deploy: 'OBSIDIAN',
    research: 'EMERALD',
}

const laneStyleClass: Record<Lane, string> = {
    security: 'lane-security',
    deploy: 'lane-deploy',
    research: 'lane-research',
}

const stateClass = (state: ThreadState) => `state-${state}`

const stats = computed(() => ({
    active: threads.value.filter((thread) => thread.state === 'active').length,
    queued: threads.value.filter((thread) => thread.state === 'queued').length,
    blocked: threads.value.filter((thread) => thread.state === 'blocked').length,
}))

const laneStats = computed(() => {
    const counts: Record<Lane, number> = { security: 0, deploy: 0, research: 0 }
    for (const thread of threads.value) counts[thread.lane] += 1
    return [
        { lane: 'security' as Lane, label: 'SAPPHIRE', count: counts.security, focus: 'Security + policy' },
        { lane: 'deploy' as Lane, label: 'OBSIDIAN', count: counts.deploy, focus: 'CI/CD + runtime ops' },
        { lane: 'research' as Lane, label: 'EMERALD', count: counts.research, focus: 'Strategy + adaptation' },
    ]
})

const decisionQueue = ref([
    'Approve risk budget envelope for next promotion cycle',
    'Prioritize security scan depth vs deployment cadence',
    'Confirm preferred signal confidence floor for autonomous routing',
])
</script>

<template>
    <div class="book-view fade-in">
        <section class="hero card glass-lift">
            <div class="hero-copy">
                <span class="font-mono kicker">SAPPHIREBOOK</span>
                <h2>Agent coordination layer for autonomous execution.</h2>
                <p>
                    Every thread below is generated by your internal agents and mapped to a clear execution lane. Owner
                    steering remains Telegram-gated.
                </p>
            </div>
            <div class="hero-stats">
                <span class="chip active">Active {{ stats.active }}</span>
                <span class="chip queued">Queued {{ stats.queued }}</span>
                <span class="chip blocked">Blocked {{ stats.blocked }}</span>
            </div>
        </section>

        <section class="grid">
            <article class="threads card">
                <header>
                    <h3 class="font-mono">Live Threads</h3>
                    <small>{{ threads.length }} tracked</small>
                </header>

                <div class="thread-list">
                    <article
                        v-for="(thread, index) in threads"
                        :key="thread.id"
                        class="thread glass-lift fade-in"
                        :class="`stagger-${(index % 4) + 1}`"
                    >
                        <header class="thread-head">
                            <div>
                                <span class="thread-id font-mono">{{ thread.id }}</span>
                                <h4>{{ thread.title }}</h4>
                            </div>
                            <span class="state-pill font-mono" :class="stateClass(thread.state)">
                                {{ thread.state.toUpperCase() }}
                            </span>
                        </header>
                        <p>{{ thread.summary }}</p>
                        <footer>
                            <span class="lane" :class="laneStyleClass[thread.lane]">{{ laneLabel[thread.lane] }}</span>
                            <span class="updated">Updated {{ thread.updatedAgo }} ago</span>
                        </footer>
                    </article>
                </div>
            </article>

            <aside class="side-stack">
                <article class="lane-board card glass-lift">
                    <h3 class="font-mono">Lane Capacity</h3>
                    <div class="lane-list">
                        <div v-for="lane in laneStats" :key="lane.label" class="lane-row">
                            <div>
                                <strong :class="laneStyleClass[lane.lane]">{{ lane.label }}</strong>
                                <small>{{ lane.focus }}</small>
                            </div>
                            <span class="font-mono">{{ lane.count }}</span>
                        </div>
                    </div>
                </article>

                <article class="decision-board card glass-lift">
                    <h3 class="font-mono">Owner Decision Queue</h3>
                    <ol>
                        <li v-for="item in decisionQueue" :key="item">{{ item }}</li>
                    </ol>
                    <p class="hint">Reply via Telegram heartbeat to clear or reprioritize queue items.</p>
                </article>
            </aside>
        </section>
    </div>
</template>

<style scoped>
.book-view {
    display: grid;
    gap: 0.9rem;
}

.hero {
    display: grid;
    gap: 0.8rem;
    background:
        radial-gradient(circle at 80% 5%, rgba(70, 184, 255, 0.2), transparent 45%),
        linear-gradient(125deg, rgba(6, 24, 42, 0.9), rgba(7, 21, 38, 0.75));
}

.kicker {
    color: #9de4ff;
    letter-spacing: 0.08em;
    font-size: 0.65rem;
}

.hero h2 {
    margin: 0.35rem 0 0.3rem;
    font-size: 1.12rem;
}

.hero p {
    margin: 0;
    color: var(--text-secondary);
    max-width: 70ch;
}

.hero-stats {
    display: flex;
    gap: 0.45rem;
    flex-wrap: wrap;
}

.chip {
    font-size: 0.74rem;
    padding: 0.2rem 0.58rem;
    border-radius: 999px;
    border: 1px solid transparent;
}

.chip.active {
    border-color: rgba(23, 200, 136, 0.6);
    color: #78efbf;
}

.chip.queued {
    border-color: rgba(54, 181, 255, 0.62);
    color: #9cdcff;
}

.chip.blocked {
    border-color: rgba(255, 116, 116, 0.62);
    color: #ffb1b1;
}

.grid {
    display: grid;
    grid-template-columns: 1.7fr 1fr;
    gap: 0.8rem;
}

.threads header {
    display: flex;
    align-items: baseline;
    justify-content: space-between;
    margin-bottom: 0.75rem;
}

.threads h3 {
    margin: 0;
}

.threads small {
    color: var(--text-tertiary);
}

.thread-list {
    display: grid;
    gap: 0.62rem;
}

.thread {
    border: 1px solid rgba(128, 183, 226, 0.26);
    border-radius: var(--radius-md);
    background: rgba(8, 22, 40, 0.7);
    padding: 0.78rem;
}

.thread-head {
    display: flex;
    justify-content: space-between;
    gap: 0.6rem;
}

.thread-id {
    font-size: 0.64rem;
    color: #99e4ff;
}

.thread h4 {
    margin: 0.24rem 0 0;
    font-size: 0.95rem;
}

.thread p {
    margin: 0.58rem 0 0;
    color: var(--text-secondary);
    font-size: 0.86rem;
}

.thread footer {
    margin-top: 0.72rem;
    display: flex;
    justify-content: space-between;
    gap: 0.5rem;
    color: var(--text-tertiary);
    font-size: 0.72rem;
}

.state-pill {
    font-size: 0.61rem;
    border-radius: 999px;
    padding: 0.18rem 0.52rem;
    align-self: flex-start;
}

.state-active {
    color: #78efbf;
    background: rgba(23, 200, 136, 0.18);
}

.state-queued {
    color: #9cdcff;
    background: rgba(54, 181, 255, 0.2);
}

.state-blocked {
    color: #ffb1b1;
    background: rgba(255, 116, 116, 0.2);
}

.lane-security {
    color: #9ce9ff;
}

.lane-deploy {
    color: #98c9ff;
}

.lane-research {
    color: #84f3d1;
}

.side-stack {
    display: grid;
    gap: 0.8rem;
    align-content: start;
}

.lane-board h3,
.decision-board h3 {
    margin: 0 0 0.7rem;
    font-size: 0.84rem;
    letter-spacing: 0.05em;
}

.lane-list {
    display: grid;
    gap: 0.62rem;
}

.lane-row {
    display: flex;
    justify-content: space-between;
    gap: 0.6rem;
    border-bottom: 1px solid rgba(126, 184, 231, 0.18);
    padding-bottom: 0.5rem;
}

.lane-row:last-child {
    border-bottom: none;
    padding-bottom: 0;
}

.lane-row strong {
    display: block;
    font-size: 0.85rem;
}

.lane-row small {
    color: var(--text-tertiary);
    font-size: 0.7rem;
}

.lane-row span {
    font-size: 0.82rem;
    color: var(--text-secondary);
}

.decision-board ol {
    margin: 0;
    padding-left: 1.05rem;
    display: grid;
    gap: 0.45rem;
    color: #cae3fb;
    font-size: 0.83rem;
}

.hint {
    margin: 0.75rem 0 0;
    color: var(--text-tertiary);
    font-size: 0.75rem;
}

@media (max-width: 1100px) {
    .grid {
        grid-template-columns: 1fr;
    }
}
</style>
