"""Unit tests for `lib.pine.static_analyzer`.

Pins current analyzer behavior so future edits to either the analyzer or
`lib.trading.pine_templates` don't silently drift the Pine ↔ webhook
contract. Tests run without the `tv` CLI — they exercise the offline
pattern-matching path only.
"""

from __future__ import annotations

from lib.pine import analyze_pine_file, analyze_pine_source
from lib.trading.pine_templates import (
    render_sapphire_screener,
    render_sapphire_watch_indicator,
    render_sapphire_watch_strategy,
)

# ---------------------------------------------------------------------------
# Generator output: indicator / strategy / screener should pass clean.
# ---------------------------------------------------------------------------


def test_generator_indicator_passes_clean():
    src = render_sapphire_watch_indicator("BINANCE:ETHUSDT")
    result = analyze_pine_source(src)
    assert result == {"ok": True, "errors": [], "warnings": []}


def test_generator_strategy_passes_clean():
    src = render_sapphire_watch_strategy("BINANCE:ETHUSDT")
    result = analyze_pine_source(src)
    assert result == {"ok": True, "errors": [], "warnings": []}


def test_generator_screener_passes_clean():
    src = render_sapphire_screener(["BINANCE:ETHUSDT", "BINANCE:BTCUSDT"])
    result = analyze_pine_source(src)
    assert result == {"ok": True, "errors": [], "warnings": []}


# ---------------------------------------------------------------------------
# Production hand-authored strategy is the regression guard.
# ---------------------------------------------------------------------------


def test_production_mac_strategy_passes_clean():
    result = analyze_pine_file("pine/standalone/Sapphire_Strategy_Mac.pine")
    assert result["ok"] is True
    assert result["errors"] == []
    assert result["warnings"] == []
    # path is preserved on the file-form result
    assert result["path"].endswith("Sapphire_Strategy_Mac.pine")


# ---------------------------------------------------------------------------
# Failure modes: one canned source per check.
# ---------------------------------------------------------------------------


def test_legacy_ts_field_triggers_contract_drift_error():
    # Sapphire-tagged source so Sapphire-only checks also run; the `"ts":`
    # check is global, but tagging makes the source realistic.
    src = (
        "// Auto-generated by Sapphire (lib.trading.pine_templates)\n"
        "//@version=5\n"
        'indicator("X", overlay=true)\n'
        'alert(\'{"symbol": "BTC", "action": "long", "price": 1.0, '
        '"time": 1, "ts": 1}\', alert.freq_once_per_bar_close)\n'
    )
    result = analyze_pine_source(src)
    ts_errors = [e for e in result["errors"] if '"ts"' in e["msg"]]
    assert len(ts_errors) == 1
    assert ts_errors[0]["line"] == 4
    assert result["ok"] is False


def test_strategy_entry_without_matching_close_warns():
    src = (
        "// Auto-generated by Sapphire (lib.trading.pine_templates)\n"
        "//@version=5\n"
        'strategy("X", overlay=true)\n'
        'strategy.entry("Long", strategy.long)\n'
        'alert(\'{"symbol": "x", "action": "long", "price": 1.0, '
        '"time": 1}\', alert.freq_once_per_bar_close)\n'
    )
    result = analyze_pine_source(src)
    pairing = [w for w in result["warnings"] if 'strategy.entry("Long"' in w["msg"]]
    assert len(pairing) == 1
    # No errors — pairing miss is a warning, not a hard fail.
    assert result["ok"] is True


def test_missing_version_declaration_errors():
    src = 'indicator("X", overlay=true)\n'
    result = analyze_pine_source(src)
    version_errors = [e for e in result["errors"] if "//@version=5" in e["msg"]]
    assert len(version_errors) == 1
    assert result["ok"] is False


def test_both_indicator_and_strategy_top_level_errors():
    src = '//@version=5\nindicator("X")\nstrategy("Y")\n'
    result = analyze_pine_source(src)
    multi = [e for e in result["errors"] if "expected exactly one top-level" in e["msg"]]
    assert len(multi) == 1
    assert result["ok"] is False


# ---------------------------------------------------------------------------
# Row shape contract: every row has a 1-indexed int `line` and a str `msg`.
# ---------------------------------------------------------------------------


def test_error_and_warning_rows_have_line_and_msg_shape():
    # Force at least one error AND one warning in a single source so we can
    # assert the row shape on both.
    src = (
        "// Auto-generated by Sapphire (lib.trading.pine_templates)\n"
        "//@version=5\n"
        'strategy("X", overlay=true)\n'
        'strategy.entry("Long", strategy.long)\n'
        'alert(\'{"symbol": "x", "action": "long", "price": 1.0, '
        '"time": 1, "ts": 1}\', alert.freq_once_per_bar_close)\n'
    )
    result = analyze_pine_source(src)
    assert result["errors"], "expected at least one error in this canned source"
    assert result["warnings"], "expected at least one warning in this canned source"
    for row in (*result["errors"], *result["warnings"]):
        assert set(row.keys()) >= {"line", "msg"}
        assert isinstance(row["line"], int)
        assert row["line"] >= 1
        assert isinstance(row["msg"], str)
        assert row["msg"]
